### PR TITLE
Add Bunny DNS API verification method

### PR DESCRIPTION
**Pull request by nosilver4u**
Adds DNS verification for domains using Bunny DNS.

### CODE REVIEW

**Comment by nosilver4u** [comment]
All tests passed with HTTPS verification disabled per #4287. I had to re-run the DragonflyBSD test, but it succeeded the second time around. I would note that there was no debug output on DragonflyBSD to find what actually failed, as the --debug param appeared to be missing from the acme.sh call:
`  /root/.acme.sh/acme.sh --server "letsencrypt_test"  --issue -d "***" -d "*.***" --dns *** --dnssleep "***"  [FAIL] 
`

**Comment by nosilver4u** [comment]
Ugh, just realized the shebang got set to bash. I've fixed that, but not sure if I can update the pull request or have to make a new one. I'll check after the test suite is done running on the latest commit to my fork.

**Comment by Neilpang** [comment]
image

**Comment by nosilver4u** [comment]
Well, I added a section to the wiki, and now it won't render!
https://github.com/acmesh-official/acme.sh/wiki/dnsapi

Just to see if it was my fault, I removed the section and checked the preview, but it still fails. I checked the diff to make sure I didn't add anything unexpected, but I don't know how to "fix" it now.

**Comment by Neilpang** [comment]
It seems the wiki page is too large to render, let me fix it.
Thanks

**Comment by Neilpang** [comment]
>> Not sure if it matters currently, but I don't think dns_dgon.sh would pass the test suite since the script doesn't reset the value 

I would appreciate it if you can fix the code.  since I don't have an account to test.

**Comment by nosilver4u** [comment]
> > > Not sure if it matters currently, but I don't think dns_dgon.sh would pass the test suite since the script doesn't reset the value
> 
> I would appreciate it if you can fix the code. since I don't have an account to test.

Will give it a shot and see how it goes!

**Pull request merged**
