### PR TITLE
Add support for Lima-City

### PR DESCRIPTION
**Pull request by laraveluser**
Add support for Lima-City. 

Unfortunally the DNS-Test fails because of not installable opensuse/leap:latest. This must be a bug in the Testsystem. The other Tests until then are fine.

### CODE REVIEW

**Comment by Neilpang** [comment]
The test system has no problem.  please re-run your tests

**Comment by laraveluser** [comment]
Rerun also failed, but I can't see an ACME related error in the logfile. For me it looks like a bug in the test system:

> [Sat Aug 26 20:43:10 UTC 2023] Using config home:/root/.acme.sh
> [Sat Aug 26 20:43:10 UTC 2023] ACME_DIRECTORY='https://acme-staging-v02.api.letsencrypt.org/directory'
> [Sat Aug 26 20:43:10 UTC 2023] _ACME_SERVER_HOST='acme-staging-v02.api.letsencrypt.org'
> [Sat Aug 26 20:43:10 UTC 2023] _ACME_SERVER_PATH='directory'
> [Sat Aug 26 20:43:10 UTC 2023] The keys and certs are in "/root/.acme.sh", you can remove them by yourself.
>
> ------------------------------------------
> #0 building with "default" instance using docker driver
> 
> #1 [internal] load .dockerignore
> #1 transferring context: 2B done
> #1 DONE 0.0s
> 
> #2 [internal] load build definition from Dockerfile
> #2 transferring dockerfile: 156B done
> #2 DONE 0.0s
> 
> #3 [internal] load metadata for docker.io/library/alpine:latest
> #3 DONE 0.1s
> 
> #4 [1/2] FROM docker.io/library/alpine:latest@sha256:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a
> #4 DONE 0.0s
> 
> #5 [2/2] RUN apk update -f 2>&1 && apk --no-cache add -f openssl curl socat libidn libc6-compat wget  2>&1
> #5 CACHED
> 
> #6 exporting to image
> #6 exporting layers done
> #6 writing image sha256:65698dd7e7ca0d4218910aa2b4abb1e3d18359c72e618e16a543b03d6518684c done
> #6 naming to docker.io/library/myalpine:latest done
> #6 DONE 0.0s
> [Sat Aug 26 20:43:10 UTC 2023] Failed: alpine:latest
> Error: Process completed with exit code 1.

**Comment by Neilpang** [comment]
please rebase to the latest dev branch first.

**Comment by laraveluser** [comment]
What do you mean by rebase? A synchronization with the current branch and then a new pull request?

The test system is still not running. At the moment it hangs on FreeBSD, which I can't understand, because I scripted it for OPNsense and it works there.

Before the last commit there was actually an error, because obviously the escape rules are different in FreeBSD.

**Comment by laraveluser** [comment]
I don't understand why the test keeps failing even though the DNS records are written and also deleted. Since the script works for my purposes, it is annoying to adjust the configuration every time OPNsense is updated, but less time consuming than continuing to try here with no comprehensible error messages. 

If the pull request cannot be merged, please close it, otherwise please merge it.

**Comment by Neilpang** [comment]
It  seems a lot of dns test have already passed. 
The netBSD test is failing.  please update your code to the latest dev code, it will run your dns test again. 
Let's see what will happend.

**Comment by feroxib** [comment]
can i expect this to be in the next release?
as it is already part in acme.sh-master

**Pull request merged**
