### PR TITLE
Consul deploy hooks

### PR DESCRIPTION
**Pull request by bgarret**
Consul API and CLI deploy hooks, inspired by the Vault deploy hooks.

### CODE REVIEW

**Comment by Neilpang** [comment]
why are there 2 hooks?
why not make them as one?

Default behavior: find and use cli first if cli exists, otherwise,  try to us API.
There can also be a variable  : `USE_CLI` to force to use cli.

**Comment by bgarret** [comment]
There are 2 hooks because the Vault integration is structured this way, I used it as a reference and did not think too much on it.

Your way is indeed better, I'll update the pull request with the modifications, and update the wiki docs once the pull request is merged.

Thanks!

**Comment by bgarret** [comment]
Changes done

**Comment by bgarret** [comment]
Do you need something else to get this merged? I'm happy to help in any way I can.

**Pull request merged**
