### PR TITLE
Fix simply.com API

### PR DESCRIPTION
**Pull request by tomsommer**
- Normalize JSON and fix not handling return code correctly
- Add some information to comments
- Fix trailing slash on URIs
- Add 60 second sleep for zone to be written

### CODE REVIEW

**Comment by Neilpang** [comment]
don't rename the api.   the existing users need it to renew the cert.

**Comment by tomsommer** [comment]
Fixed

**Comment by Neilpang** [comment]
fix the CI tests:
https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test

**Comment by jakelamotta** [comment]
Thank you for fixing this, it would be awesome if the CI tests could be fixed so it can be merged.

**Comment by jvandborg** [comment]
@tomsommer It would be great, if you could fix the CI tests, so your changes can be merged into the main release of acme.sh. I'm eagerly awaiting the patches to update my UDMP with SSL-certificate.

**Pull request closed without merging**
