### PR TITLE
Aws dns imdsv2

### PR DESCRIPTION
**Pull request by derytim**
This uses IMDSv2 on EC2 instances, if available. (I don't think you can launch an instance that ONLY supports IMDSv1. If you had an instance running for years, maybe it doesn't support IMDSv2).

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html
https://aws.amazon.com/blogs/security/get-the-full-benefits-of-imdsv2-and-disable-imdsv1-across-your-aws-infrastructure/

Tested this on an EC2 instance using just IMDSv2, using both, and using both (but forcing it to use IMDSv1).

https://github.com/acmesh-official/acme.sh/issues/4960

### CODE REVIEW

**Comment by derytim** [comment]
I've read the docs. This isn't a new DNS API integration, just an addition to an already-existing integration.

**Comment by derytim** [comment]
> **Welcome** Please make sure you've read our [DNS API Dev Guide](../wiki/DNS-API-Dev-Guide) and [DNS-API-Test](../wiki/DNS-API-Test). Then reply on this message, otherwise, your code will not be reviewed or merged. We look forward to reviewing your Pull request shortly ✨ 注意: 必须通过了 [DNS-API-Test](../wiki/DNS-API-Test) 才会被 review. 无论是修改, 还是新加的 dns api, 都必须确保通过这个测试.

I've read the docs. This isn't a new DNS API integration, just an addition to an already-existing integration.

**Comment by derytim** [comment]
The OpenBSD tests are failing. Relevant output is:
```
  [Thu Feb  1 22:48:32 UTC 2024] Found domain api file: /root/.acme.sh/dnsapi/***.sh
  [Thu Feb  1 22:48:32 UTC 2024] Load file /root/.acme.sh/dnsapi/***.sh error. Please check your api file and try again.
  [Thu Feb  1 22:48:32 UTC 2024] _on_issue_err
  [Thu Feb  1 22:48:32 UTC 2024] Please check log file for more details: le_test_dnsapi.log
```
The tests have passed on Docker, MacOS, Windows, and FreeBSD.
Can you point me in a next direction?

**Comment by derytim** [comment]
https://github.com/derytim/acme.sh/actions/runs/7734909136

**Comment by Neilpang** [comment]
you can get a openbad vm here to debug:
https://github.com/vmactions/shell-openbsd

**Comment by derytim** [comment]
I ran the tests against the bare fork (without my changes), and the OpenBSD automated tests appear to have failed in the same way - output looks like cert was generated, but the test still fails. 
https://github.com/derytim/acme.sh/actions/runs/7924505475/job/21638722100
I think the test is bad, or something else is broken unrelated to my changes.

**Comment by j-c-m** [comment]
_use_metadata() is broken on OpenBSD, I don't think many DNS APIs were originally tested at all under OpenBSD (ksh).

**Comment by j-c-m** [comment]
https://github.com/j-c-m/acme.sh/commit/e2de58aa8fb14f91aa94b8626916c5a0b6f3f482

That might fix it? I don't have any test environment available for route53/aws.

**Comment by derytim** [comment]
> [j-c-m@e2de58a](https://github.com/j-c-m/acme.sh/commit/e2de58aa8fb14f91aa94b8626916c5a0b6f3f482)
> 
> That might fix it? I don't have any test environment available for route53/aws.
Thanks @j-c-m , that change did get me past the OpenBSD tests.

It then failed on NetBSD tests :(
``` Run onInitialized in VM
  exec shell: bash run.sh onInitialized
  /usr/bin/bash
  Config file: netbsd-9.3.conf
Run 'prepare' in VM
  Running prepare: pkg_add curl socat
  
  exec ssh: pkg_add curl socat
  /usr/bin/bash /home/runner/work/_actions/vmactions/netbsd-vm/v1/run.sh execSSHSH
  Config file: netbsd-9.3.conf
  sh: pkg_add: not found
  Error: The process '/usr/bin/bash' failed with exit code 127 ```

**Comment by j-c-m** [comment]
That looks like an error in the vm setup, from the actions just re-run the failed jobs, should pass.

**Comment by derytim** [comment]
No dice, same error. Setup can't find `pkg_add`. It's called in the tests here https://github.com/acmesh-official/acmetest/blob/master/.github/workflows/NetBSD.yml#L47 
From the error I'm guessing it isn't at `/usr/sbin/pkg_add`, but I'm not familiar with BSD so that's just a guess.

**Comment by Neilpang** [comment]
rebase your code to the latest dev branch first.

**Comment by j-c-m** [comment]
Yep that’s it, his feature branch is missing b79c3f5

**Comment by derytim** [comment]
Thanks, that seemed to do it.

**Comment by Neilpang** [comment]
do you need to update the usage here? 
https://github.com/acmesh-official/acme.sh/wiki/dnsapi#10-use-amazon-route53-domain-api

**Comment by pipozzz** [comment]
Hi, I upgraded acme.sh and try rerun --renew command but no luck. I'm getting this error:

```<ErrorResponse xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><Error><Type>Sender</Type><Code>InvalidClientTokenId</Code><Message>The security token included in the request is invalid.</Message></Error><RequestId>3e91a42b-8398-4a6b-96e6-f3105b08eb21</RequestId></ErrorResponse>'
[Wed Apr 10 11:27:27 UTC 2024] Response error:<?xml version="1.0"?>
<ErrorResponse xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><Error><Type>Sender</Type><Code>InvalidClientTokenId</Code><Message>The security token included in the request is invalid.</Message></Error><RequestId>3e91a42b-8398-4a6b-96e6-f3105b08eb21</RequestId></ErrorResponse>
```
  

When I try to get role credentials manually from metadata service it works but using acme.sh

**Pull request merged**
