### PR TITLE
[dns_pdns] Fix: missing content type in PATCH requests

### PR DESCRIPTION
**Pull request by NaPs**
Fix a "Request is not json" error when PATCHing on PowerDNS(-Admin) API.

Before:

```
[Sun 21 Mar 16:18:19 CET 2021] PATCH
[Sun 21 Mar 16:18:19 CET 2021] _post_url='http://10.10.10.10:8081/api/v1/servers/localhost/zones/example.org.'
[Sun 21 Mar 16:18:19 CET 2021] body='{"rrsets": [{"changetype": "REPLACE", "name": "_acme-challenge.test.example.org.", "type": "TXT", "ttl": 60, "records": [{"content": "\"xxx\"", "disabled": false}, {"content": "\"xxx\"", "disabled": false}, {"content": "\"qccxyKB4cll0VJko8iqWkDaGIvkZ1PLaBBX2SJgrsoI\"", "disabled": false}]}]}'
[Sun 21 Mar 16:18:19 CET 2021] _postContentType
[Sun 21 Mar 16:18:19 CET 2021] Http already initialized.
[Sun 21 Mar 16:18:19 CET 2021] _CURL='curl --silent --dump-header /home/antoine/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.dv5dhswaCA  -g '
[Sun 21 Mar 16:18:19 CET 2021] _ret='0'
[Sun 21 Mar 16:18:19 CET 2021] response='{"msg": "Request is not json"}'
[Sun 21 Mar 16:18:19 CET 2021] data
```

After:

```
[Sun 21 Mar 16:17:23 CET 2021] PATCH
[Sun 21 Mar 16:17:23 CET 2021] _post_url='http://10.10.10.10:8081/api/v1/servers/localhost/zones/example.org.'
[Sun 21 Mar 16:17:23 CET 2021] body='{"rrsets": [{"changetype": "REPLACE", "name": "_acme-challenge.test.example.org.", "type": "TXT", "ttl": 60, "records": [{"content": "\"xxx\"", "disabled": false}, {"content": "\"xxx\"", "disabled": false}]}]}'
[Sun 21 Mar 16:17:23 CET 2021] _postContentType='application/json'
[Sun 21 Mar 16:17:23 CET 2021] Http already initialized.
[Sun 21 Mar 16:17:23 CET 2021] _CURL='curl --silent --dump-header /home/antoine/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.mQvytAS2Hj  -g '
[Sun 21 Mar 16:17:24 CET 2021] _ret='0'
[Sun 21 Mar 16:17:24 CET 2021] response
[Sun 21 Mar 16:17:24 CET 2021] data
```

### CODE REVIEW

**Comment by Neilpang** [comment]
can you please fix the CI checks first?
https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test

**Comment by NaPs** [comment]
@Neilpang Do you confirm that I need to setup a powerdns server on my own infrastructure to run this test or I missed something?

**Comment by NaPs** [comment]
Ok so I fixed it, the DNS job is now passing but the solaris job is failing. Do I need to fix it?

https://github.com/NaPs/acme.sh/actions/runs/681317463

**Comment by Neilpang** [comment]
yes

**Comment by funzoneq** [comment]
This got merged as part of #3572

**Pull request closed without merging**
