### PR TITLE
deploy hook: routeros: store the env vars within the domainconf

### PR DESCRIPTION
**Pull request by herbetom**
I edited the deploy hook for RouterOS so that the enviroment variables for the routeros deploy hook are now stored inside the domain configuration file, so that it is not necessary to provide them each time. 
Also the option `ROUTER_OS_WEB_SERVICE` with the default value `yes` was added for the ability to disable updating the certificate for the www-ssl service, useful for example when a special certificate only for the hotspot server is needed.

This changes shouldn't cause an issue for current users of the deploy hook.

### CODE REVIEW

**Comment by cngarrison** [comment]
@herbetom Could you please fix the failing test(s). 

I had a quick review of the changes and looks fine. I'll review in detail once the tests pass. 

(Yes, I know - took me a while to fix the script so it would pass all tests. Have a look as `shfmt`; I suspect that will be the why its failing.)

And thanks for creating the PR; it's the first one since I took over the `routeros` deploy hook. ;-)

**Comment by herbetom** [comment]
@cngarrison Yeah, it seems to be a problem with the `shfmt` check. But the current script doesn't work for me. As i already reported https://github.com/Neilpang/acme.sh/issues/2344#issuecomment-514880505, RouterOS just returns `syntax error`. It seems to have something to do with the line breaks in the var `DEPLOY_SCRIPT_CMD`. A quick try to do it diffrent https://github.com/Neilpang/acme.sh/pull/2413/commits/faa84a42c3dafb1db764a03756ee24996531866e wasn't succesfull. Any ideas?

**Comment by cngarrison** [comment]
Had an availability incident at $work this week, so no time to reply properly yet. My quick answer; I used an online `shfmt` formatter to keep tweaking the code until it was expected format. I can't find that online formatter right now. I'll try to have a look at the changes soon and maybe I'll see something familiar to fix the shell formatting.

**Comment by cngarrison** [comment]
Sorry it's taken me so long to return to this - I didn't have spare brain cycles for it before. Unfortunately, I don't know `shfmt` well enough to suggest why it's failing. The code changes look fine to me.

**Comment by cngarrison** [comment]
I did a PR with the trailing slashes and it passed the CI build/test. Once it gets merged, would you please update this PR and see if your changes to store vals inside the domain configuration file will build/test ok.

**Comment by herbetom** [comment]
Yes, once your pull request #2604 has been merged and I find the time I will do it.

**Comment by herbetom** [comment]
Have you already looked into [RouterOS v7 (beta)](https://mikrotik.com/download/changelogs/development-release-tree)? They write in the changelog:

> New CLI style which is more similar to API commands (v6 commands still supported)

So hopefully it will still work. But who knows. It should probably be tested.

**Comment by cngarrison** [comment]
I’m aware of v7 but haven't looked into it. Thanks for the changelog entry. 

> ... (v6 commands still supported)

I read that to mean the current command style/syntax will still work. But agreed, needs to be tested.

**Comment by aklowther** [comment]
@herbetom @cngarrison any chance this could get another look?

**Comment by herbetom** [comment]
I currently don't have time to look into this. Sorry

**Pull request closed without merging**
