### PR TITLE
Fix deploy script for Synology DSM (wrong RegEx for path extraction)

### PR DESCRIPTION
**Pull request by Eagle3386**
Fixes wrong RegEx as mentioned in corresponding [deploy API issue](https://github.com/acmesh-official/acme.sh/issues/2727#issuecomment-1733927132).

Really don't know, how that'd slipped through, because I wrote the correct RegEx just a couple of comments above the linked one… 🙈😅

Anyway, this fixes the issue once & for all. 😎

### CODE REVIEW

**Comment by Eagle3386** [comment]
@Neilpang I don't know why GitHub states "branch conflict" for simply changing the RegEx range from `0-9` to `a-z.`… 🤔

**Comment by winromulus** [comment]
@Eagle3386  PR #4809 was already merged. Probably that's why you get conflicts.

**Comment by winromulus** [comment]
@Eagle3386 considering Synology's naming conventions, I wouldn't assume that the entry will not contain any numeric or other characters in the path. Ideally this would have been picked up using jq instead of sed.

**Comment by Eagle3386** [comment]
> @Eagle3386 PR #4809 was already merged. Probably that's why you get conflicts.

Probably not,because if it wasn't, my PR would still change the exact same RegEx range.
If it wasn't merged already that'd make sense, but it is, so…

> @Eagle3386 considering Synology's naming conventions, I wouldn't assume that the entry will not contain any numeric or other characters in the path. Ideally this would have been picked up using jq instead of sed.

I've never come across an API endpoint of them that uses numbers. Other chars might be, but again, never seen that up to now.
Using jq would've been an option, yes - especially, since the file header even mentions it as a requirement.
However, neither the original script nor my update actually used it before & so I opted to follow the current way. That's because AFAIK jq isn't available by default on all platforms & Neil's requirement is to write cross platform compatible code, using "standard tools".

**Pull request closed without merging**
