### PR TITLE
Upgrade Travis image

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by szepeviktor** [comment]
No CI for PRs??

**Comment by Neilpang** [comment]
@szepeviktor     There must be something wrong recently,  the CI for PR is not working.
I'm checking.

**Comment by Neilpang** [comment]
you can open the travis page to check the result: 
https://travis-ci.org/acmesh-official/acme.sh

**Comment by szepeviktor** [comment]
Thank you for your answer.

I think it is okay to use a modern Ubuntu release.
Only few shellcheck rules has been triggered: https://travis-ci.org/github/acmesh-official/acme.sh/jobs/708435689

**Comment by Neilpang** [comment]
can you please fix that issue also ?

**Comment by szepeviktor** [comment]
Done.

**Comment by szepeviktor** [comment]
Somehow `deploy/openstack.sh`˙got into my PR :(

**Comment by szepeviktor** [comment]
Thank you.

**Pull request merged**
