### PR TITLE
Add support for DNSmanager from company ispsystem

### PR DESCRIPTION
**Pull request by kvakanet**
Add support for DNSmanager from company ispsystem
product description: https://www.ispsystem.com/software/dnsmanager

### CODE REVIEW

**Comment by Neilpang** [comment]
please fix the CI errors first:
https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test

**Comment by kvakanet** [comment]
Can i use TokenName3 and TokenValue3 for url service provider?

**Comment by Neilpang** [comment]
please update to the latest code.
you can  TokenName3, TokenName4 and TokenName5 now.

Thanks.

**Comment by kvakanet** [comment]
I updated.
May be problem in upper case secretname ?
I create secret with name TestName, but created TESTNAME .

**Comment by Neilpang** [comment]
No, I don't think it's case sensitive.

**Comment by kvakanet** [comment]
ok. I checked over API secret TokenName1
```
GET https://api.github.com/repos/kvakanet/acme.sh/actions/secrets/TokenName1 
{
  "name": "TOKENNAME1",
  "created_at": "2020-09-12T15:59:50Z",
  "updated_at": "2020-09-12T15:59:50Z"
}
```
But CI test Fail. 
Maybe your script(CI if [ "${{secrets.TokenName1}}" ] ; then ) cannot access my secrets ?

**Comment by Neilpang** [comment]
It seems the PR can not access the Secrets of your fork.
Please enable the github actions for your fork and run the CI tests there first.
I'm thinking about how to fix it.

**Comment by kvakanet** [comment]
I checked own repo(dev branch). MacOS - Fail (curl error 6)
Docker - good, but curl error 6 
```
[Tue Sep 15 17:09:19 UTC 2020] _CURL='curl -L --silent --dump-header /Users/runner/.acme.sh/http.header  -g '
[Tue Sep 15 17:09:19 UTC 2020] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[Tue Sep 15 17:09:19 UTC 2020] _ret='6'
[Tue Sep 15 17:09:19 UTC 2020] error *** find domain
[Tue Sep 15 17:09:19 UTC 2020] invalid domain
[Tue Sep 15 17:09:19 UTC 2020] Error add txt for domain:_acme-challenge.***
[Tue Sep 15 17:09:19 UTC 2020] _on_issue_err
[Tue Sep 15 17:09:19 UTC 2020] Please check log file for more details: le_test_dnsapi.log
```

**Pull request closed without merging**
