### PR TITLE
Use short User agent options

### PR DESCRIPTION
**Pull request by stokito**
The shorter makes the command line shorter and easier to understood. Other options already uses short form when possible.

### CODE REVIEW

**Comment by Neilpang** [comment]
the langer form is easier to understand than the short form.

**Comment by stokito** [comment]
The `-U "$USER_AGENT"` is self explanatory

**Comment by Neilpang** [comment]
I don't think '-U'  is easier to read than `--user-agent`.
And the source code is not for the end user, so, nobody would care about that.
When we change the code, there is a risk that the short option is not supported by some of the platforms, on which it used to run.
So, it brings almost nothing benefit to us,  just more risk. It's not worth that.

**Comment by stokito** [comment]
Well, if you carry about other platforms support then it's better to use short options because BusyBox wget may be compiled without long options (but still --header doesn't have a short form).
Anyway, thank you for responding

**Pull request closed without merging**
