### PR TITLE
Add NextDNS as a DOH option.

### PR DESCRIPTION
**Pull request by jonwltn**

### CODE REVIEW

**Comment by Neilpang** [comment]
why do you need this ?

**Comment by jonwltn** [comment]
No need. Options are nice to have. I started looking into DOH options when Cloudflare didn't update their cache before the DNS check timed out. I was really glad to see Google as a secondary option.

**Comment by Neilpang** [comment]
Are both cf and google not working for you ?

**Comment by jonwltn** [comment]
I have not had an instance of when both CF and Google were not working for me. Options are nice to have, but it's not like this PR is fixing a bug or anything. Reject it if you don't want it.

**Pull request closed without merging**
