### PR TITLE
Adds DNS-API support for Simply.com

### PR DESCRIPTION
**Pull request by jakelamotta**
Adds DNS-API support for Simply.com

### CODE REVIEW

**Comment by Neilpang** [comment]
please rebase to the latest dev code.
and read this guide first: https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Dev-Guide

Thanks.

**Comment by jakelamotta** [comment]
> please rebase to the latest dev code.
> and read this guide first: https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Dev-Guide
> 
> Thanks.

Thanks. I think I have gone through all the points in the guide now. Had not updated the dns usage wiki or added the issue for bug reporting. 

However the automatic DNS check still fails. I have rebased onto dev and got the latests fix so I get a little bit further. Now failing on the FreeBSD step rather than the Windows step. Do you know about any bug in this action step?

**Comment by Neilpang** [comment]
please rebase to latest code first.

And if your need a freebsd vm to debug, check this project:  https://github.com/vmactions/shell-freebsd

You will also need a solaris vm to debug: https://github.com/vmactions/shell-solaris

**Comment by jakelamotta** [comment]
> please rebase to latest code first.
> 
> And if your need a freebsd vm to debug, check this project: https://github.com/vmactions/shell-freebsd
> 
> You will also need a solaris vm to debug: https://github.com/vmactions/shell-solaris

The code is up to date with latest from dev. 

And now all the DNS test steps succeed, it might have been the dns sleep timing which I increased slightly. Other than that I didnt change anything.

**Pull request merged**
