### PR TITLE
Add ArtFiles.de DNS API plugin

### PR DESCRIPTION
**Pull request by Eagle3386**
Usage instructions already added to [DNS API guide](https://github.com/acmesh-official/acme.sh/wiki/dnsapi2#143-use-artfilesde-dns-api).

### CODE REVIEW

**Comment by Eagle3386** [comment]
@Neilpang Please approve my first contribution so that Actions run.
Usage instructions already added, see PR's initial comment for details.

**Comment by Eagle3386** [comment]
Pinging @Neilpang as a kind reminder since I'm eagerly waiting to see this plugin merged into ACME… 😍

**Comment by Eagle3386** [comment]
How to re-issue the checks _without_ another commit? Because back in the days, some checks where broken under certain circumstances, i. e. nowadays might succeed without any change…

**Comment by Neilpang** [comment]
https://github.com/Eagle3386/acme.sh/actions/runs/2507553697


please read the doc first:


https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test

**Comment by Eagle3386** [comment]
> https://github.com/Eagle3386/acme.sh/actions/runs/2507553697

Job(s) re-run, no error message given - just Docker step idling & GitHub canceling after 6 hours of doing _nothing_.

> please read the doc first:
> 
> https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test

I _did_ read thos docs. I've read it about 23 times, but there's not a single _helpful_ notice on what to do if Docker gives _zero_ errors & _zero_ information about what it did for 6 hours.

Those docs are pretty good for setup, but _totally_ useless regarding _any_ occurring error or - as in my case - _zero_ error & _zero_ information for why Docker idled ~6 hours & GitHub then terminating it.

So, for code's sake, either tell me how to find the error, enable the debug logs to actually show _something_ useful or just merge this PR as I run it every ~60 days on my own systems successfully without _any_ errors, hence - in theory at least - already passing those darn tests.

**Comment by Eagle3386** [comment]
@Neilpang Fixed all bugs & the tests succeeded - due to API write limits of my provider (not more than 50 API write calls per day for each domain), I could only execute the full DNS test suite over the course of several days…

Still, the tests succeeded, so I'm looking forward to your merge of my DNS API addition to ACME.sh.
If anything still needs further polishing, please let me know!

**Comment by Neilpang** [comment]
It seems you didn't read the guide carefully:
https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Dev-Guide

image

**Comment by Eagle3386** [comment]
@Neilpang Created the issue & added the URL as requested.

Though, now `shfmt` complains about a line within `_egrep_o()` within the `acme.sh` file that I didn't even touch at all & there's no commit in your repo to sync my fork with so please fix that on your end to resolve `shfmt`'s error on any fork's end, thanks.

**Comment by Neilpang** [comment]
did you add the usage?

https://github.com/acmesh-official/acme.sh/wiki/dnsapi2

**Comment by Neilpang** [comment]
can you please check this guide one by one?
https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Dev-Guide

**Comment by Eagle3386** [comment]
> did you add the usage?
> 
> https://github.com/acmesh-official/acme.sh/wiki/dnsapi2

Are you serious? You'd just have to search `ArtFiles` over there & _immediately_ would've found [`143. Use ArtFiles.de DNS API`](https://github.com/acmesh-official/acme.sh/wiki/dnsapi2#143-use-artfilesde-dns-api).

**Comment by Eagle3386** [comment]
> can you please check this guide one by one? https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Dev-Guide

Can you please accept the fact that my script is ready for merge _as well as_ *immediate* usage?
But just for the sake of pleasing you once again:

1. ✅ (doesn't really apply due to ArtFiles.de's API constraints, but where it does, it complies, too)
2. ✅
3. ✅
4. ✅
5. ✅
6. ✅
7. ✅
8. ✅
9. ✅
10. ✅
11. ✅
12. ✅

**Comment by Neilpang** [comment]
it seems the DNS test never passed:
https://github.com/Eagle3386/acme.sh/actions/runs/5699465643/job/15448404280

Can you fix it?

**Comment by Eagle3386** [comment]
> it seems the DNS test never passed: https://github.com/Eagle3386/acme.sh/actions/runs/5699465643/job/15448404280
> 
> Can you fix it?

There's nothing to fix on my end, but on yours - just as I told you [earlier](https://github.com/acmesh-official/acme.sh/pull/3959#issuecomment-1656610252), mentioning a bug in `_egrep_o()` which causes `shfmt` to fail.

Even longer ago, I [mentioned](https://github.com/acmesh-official/acme.sh/pull/3959#issuecomment-1159483713) that all bugs were fixed & the script runs just fine, even on my production system, but that sometimes the Docker script times out for no reason (at least none caused by me or my script).
Additionally, GitHub doesn't cache free job runs long enough for you to re-check them after so many days.

So, until mentioned bug in `acme.sh` is fixed by you, `shfmt` in turn doesn't complain about `_egrep_o() ` anymore & you're Docker script won't idle 6 hours for no reason at all, I'm simply unable to re-run the tests successfully.

**Comment by Neilpang** [comment]
the egrep issue was fixed,  rebase your code.

**Comment by Neilpang** [comment]
please make sure the DNS tests passing before I can merge the code.

**Comment by Eagle3386** [comment]
> the egrep issue was fixed, rebase your code.

Did so yesterday, no commits to update to - did it again right now, updated 11 commits.

> please make sure the DNS tests passing before I can merge the code.

Done, see checks above.

**Comment by Eagle3386** [comment]
@Neilpang Even tried to run all the DNS tests again (marked as `Skipped` in below's `All checks have passed`box), but the amount of systems you're forcing to be tested in 1 run are forbidden on the DNS provider's end:

```sh
[Mon Jul 31 14:***4:34 UTC 2***23] DNS API error: {"error":"daily limit for this domain exceeded","status":"ERROR"}
```

That limit is 50 API write calls within 24 hours & since each test requires at least 4 writes (1 for writing the TXT challenge value, 1 for deleting it, yet another 1 for writing the wildcard TXT challenge value & finally another 1 for deleting it), I can only test up to 12 systems.

That's why each system up to & including `oraclelinux` succeeds, but `kalilinux` fails (due to already reaching 50 API write calls upon finishing the non-wildcard TXT challenge value).

Even worse, that "50 write calls limit" is per "rolling 24 hours", i. e. I can't start at ~23:45 to execute 50 calls & get another 50 calls at 00:00 - instead, the 24-hours-timer starts whenever the first write call is executed.

The only way to work around would be splitting the `Docker` step into 2 steps, so I can run the first half, re-run the failed 2nd half 24 hours later & continue - possibly after waiting yet another 24 hours - with further steps like `MacOS` or `Windows` afterwards.

**Pull request merged**
