### PR TITLE
Add existing bearer token support to Azure DNS API

### PR DESCRIPTION
**Pull request by stbeldarborge**
The Azure DNS API only works with provided service principal credentials, or if running on a resource with a managed identity.
If you want to run it in a pre authenticated context (e.g. on a local machine which is already authenticated with `az cli` or in a GitHub Action which already has authenticated with `azure/login`), there's no way to do this.

This PR adds support to skip the authentication by providing the Bearer token.
With `az cli` the bearer token can be extracted and used in Azure DNS API with this command 
```bash
export AZUREDNS_BEARERTOKEN=$(az account get-access-token --query accessToken --output tsv)

### CODE REVIEW

**Comment by stbeldarborge** [comment]
> **Welcome** First thing: don't send PR to the master branch, please send to the dev branch instead. Please make sure you've read our [DNS API Dev Guide](../wiki/DNS-API-Dev-Guide) and [DNS-API-Test](../wiki/DNS-API-Test). Then reply on this message, otherwise, your code will not be reviewed or merged. We look forward to reviewing your Pull request shortly ✨ 注意: 必须通过了 [DNS-API-Test](../wiki/DNS-API-Test) 才会被 review. 无论是修改, 还是新加的 dns api, 都必须确保通过这个测试.

PR to dev, and code tested in forked repo.

**Comment by stbeldarborge** [comment]
While #5276 is similar, these two are not the same, as #5276 does an authentication, while this PR supports authentication outside of the acme.sh context.

**Comment by stbeldarborge** [comment]
I've ran it through shfmt locally now, so hopefully it passes shfmt this time, if you can re run the workflows please

**Comment by Neilpang** [comment]
https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test

**Comment by stbeldarborge** [comment]
Now that all checks have passed, can you merge it @Neilpang ? :)

**Comment by Neilpang** [comment]
https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test
https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test
https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test
https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test
https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test
https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test
https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test

**Comment by stbeldarborge** [comment]
@Neilpang done!
https://github.com/stbeldarborge/acme.sh/actions/runs/11272323811

Sorry, I did not understand the DNS API test documentation earlier, I thought I'd done it.
And I misunderstood some of the secrets, so that's why there are so many commits, because I had to debug what was happening.. You could squashmerge it :sweat_smile:

**Comment by maonat** [comment]
@stbeldarborge imo the functionality should get automatically the token when passing `--dns dns_azure`. Have you tested this with federated credentials on service principals + GitHub actions? I need to use acme with service principals keyless on github workflows. I'm about to test this but it might take a while.

**Comment by stbeldarborge** [comment]
absolutely, that's the exact usecase I have as well and the reason why I created this :smiley:  but would work with any context as long as it's authenticated to ARM

@Neilpang sorry to keep bothering you, but DNS API test succeeded, and it's in "production" even for others now like @maonat.. would be nice if it could get into the official release :angel:

**Comment by Neilpang** [comment]
https://github.com/stbeldarborge/acme.sh/actions/runs/11287963136

**Comment by maonat** [comment]
@Neilpang isn't this related to something else and not to the code that was implemented by @stbeldarborge? He simply merged master from this repo to his fork and that has nothing to do with his changes

**Comment by EldarBorge** [comment]
@Neilpang like I mentioned, it _does_ pass the DNS test; https://github.com/stbeldarborge/acme.sh/actions/runs/11272323811

However, you probably ran it without providing a token or a secret or any other authentication to Azure? If you ran the same workflow without authentication to Azure on master, that would fail too.

**Comment by Neilpang** [comment]
I didn't/couldnt' run the dns test , because I don't have Azure account.
what I meant was that the latest run in your fork was not success:
https://github.com/stbeldarborge/acme.sh/actions/runs/11287963136

please fix it.

**Comment by maonat** [comment]
@Neilpang Here I've ran the test on my repository I forked from @stbeldarborge.
[Here is the completed and "all green" workflow](https://github.com/maonat/acme.sh/actions/runs/11703271635)

**Comment by stbeldarborge** [comment]
@Neilpang latest run is green; https://github.com/stbeldarborge/acme.sh/actions

@maonat yeah, sorry, had other matters to attend to, but at least I've configured the secrets and re run it now!

This should prove the code is good to merge hopefully? :pray:

**Comment by Neilpang** [comment]
would any of you guys update the usage here?

https://github.com/acmesh-official/acme.sh/wiki/dnsapi#dns_azure

**Comment by stbeldarborge** [comment]
Absolutely! Updated the wiki now. :slightly_smiling_face:

**Comment by Neilpang** [comment]
write code here:
image

**Comment by stbeldarborge** [comment]
Done!

**Pull request merged**
