### PR TITLE
DNS Api for dynv6

### PR DESCRIPTION
**Pull request by StefanAbl**
This should allow for dns verification with dynv6.com, a free DNS provider in Germany.

### CODE REVIEW

**Comment by StefanAbl** [comment]
Hi @Gongming,
thanks for your reply and sorry for getting back to you so late.
Unfortunately there were some errors in the code. These should be resolved now and you can try using the script.
Thanks for using it

**Comment by Neilpang** [comment]
please check this guide first:
https://github.com/Neilpang/acme.sh/wiki/DNS-API-Dev-Guide

**Comment by StefanAbl** [comment]
@Neilpang 
> please check this guide first:
> https://github.com/Neilpang/acme.sh/wiki/DNS-API-Dev-Guide

I did read your guide, Is there anything I missed apart from points 8 through 10?
I was planing to add 9 and 10 after the PR was accepted or should I do this before?
Unfortunatly it is impossible to add two TXT records with the same name but different value with dynv6.com, so point 8 can not be fullfilled.

**Comment by StefanAbl** [comment]
I wanted to know what improvements I still need to make to get the dns_dynv6.sh file merged?

**Comment by Neilpang** [comment]
>> I was planing to add 9 and 10 after the PR was accepted or should I do this before?

please do it now.


>> Unfortunatly it is impossible to add two TXT records with the same name but different value with dynv6.com, so point 8 can not be fullfilled.

Sounds weird,  is there any official doc about this ?

**Comment by StefanAbl** [comment]
> please do it now.
Done

> Sounds weird, is there any official doc about this ?
There is not a whole lot of documentation [this ](https://dynv6.com/docs/apis) seems to be most of it. For their SSH API the best documentation ist autocompletion.   
It seems adding two txt records with the same name but different values is not possible, because the record is overwritten.

**Pull request merged**
