### PR TITLE
geoscaling DNS API

### PR DESCRIPTION
**Pull request by waldner**
DNS2 API for [Geoscaling](https://www.geoscaling.com).

### CODE REVIEW

**Comment by Neilpang** [comment]
https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Dev-Guide
https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test

**Comment by waldner** [comment]
Getting a failure but I don't thik it's related to my code, looks more like a curl/tar error... see https://github.com/waldner/acme.sh/runs/5429880019

**Comment by Neilpang** [comment]
fixed,  please re-run your actions.

**Comment by waldner** [comment]
More errors here (archlinux)... https://github.com/waldner/acme.sh/runs/5433102695

**Comment by Neilpang** [comment]
sorry,  please re-run it again.

**Comment by waldner** [comment]
Everything green now. https://github.com/waldner/acme.sh/actions/runs/1938900010

**Comment by Neilpang** [comment]
have you read this guide?

https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Dev-Guide

**Comment by waldner** [comment]
Sure. Should I also create the issue and update the docs already, or should I wait for the PR to be merged? Anything else I'm missing?

**Comment by Neilpang** [comment]
Do it first.

**Comment by waldner** [comment]
Docs [here](https://github.com/acmesh-official/acme.sh/wiki/dnsapi#143-use-geoscalingcom-dns2) and issue tracker [here](https://github.com/acmesh-official/acme.sh/issues/3969). Let me know if something else is needed.

**Pull request merged**
