### PR TITLE
Update dns_loopia.sh

### PR DESCRIPTION
**Pull request by gabbe**
Loopia API is now less tolerant so we need another "value" tag surrounding the "struct" tag

### CODE REVIEW

**Comment by gabbe** [comment]
Closes Issue https://github.com/acmesh-official/acme.sh/issues/3963

**Comment by Neilpang** [comment]
can you fix the dns ci check:
https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test

**Comment by gabbe** [comment]
Sorry, I totally missed that. I'm new to GitHub workflows so this may be a silly question: Is there a way for me to manually trigger the ci check or do I need to close this PR and open a new one now that I have enabled workflows and added the necessary secrets?

**Comment by Neilpang** [comment]
you can push a new commit to your fork.  the actions will run.

**Comment by cthart** [comment]
Any chance we can get a new release soon? This affects all Loopia customers using acme.sh
I'd rather not patch approx 30 servers, but I personally would need a new version within 3 weeks as this started on 27th of February already. I'll monitor for new releases and if there is none before the last week of march I will start patching manually then.

**Comment by gabbe** [comment]
> Any chance we can get a new release soon?
It was merged into master yesterday so you should now be able to upgrade acme.sh to 3.0.3 which includes the fix.

**Comment by cthart** [comment]
Yes, I noticed yesterday and upgraded one of my machines which has a new cert today. Upgrading the rest today. Thanks guys for fixing this.

**Pull request merged**
