### PR TITLE
Update dnsapi script for OpenProvider switched current API specifications

### PR DESCRIPTION
**Pull request by Lambiek12**
Updated the dnsapi script for OpenProvider to use their current REST APIs.

Main new feature it now allows the add/removal of **single** DNS record entry in a zone instead of having to-do a full zone overlay with all records when trying to add/remove a single entry.

Documentation for reference available at [docs.openprovider.com](https://docs.openprovider.com).

Note;
Will have to update the [documentation ](https://github.com/acmesh-official/acme.sh/wiki/dnsapi#dns_openprovider) once approved, due to breaking change in API authentication. The hashed password isn't supported anymore by OpenProvider with the current (REST) API.

### CODE REVIEW

**Comment by Lambiek12** [comment]
> **Welcome** First thing: don't send PR to the master branch, please send to the dev branch instead. Please make sure you've read our [DNS API Dev Guide](../wiki/DNS-API-Dev-Guide) and [DNS-API-Test](../wiki/DNS-API-Test). Then reply on this message, otherwise, your code will not be reviewed or merged. We look forward to reviewing your Pull request shortly ✨ 注意: 必须通过了 [DNS-API-Test](../wiki/DNS-API-Test) 才会被 review. 无论是修改, 还是新加的 dns api, 都必须确保通过这个测试.

Hopefully the [DNS-API-Test](../wiki/DNS-API-Test) is done correctly 🤞

Not very familiar with Github actions still using Azure DevOps on day-to-day tasks.

**Comment by Neilpang** [comment]
Is the old api still working ?

**Comment by Lambiek12** [comment]
Yes the old API is still online and the issue i run into early in the year where the script wasn't working, but this was fixed in the current master version this summer. Although i already started at the time to replace it with the newer REST API, finally decided to just do the PR to satisfy the request in #2104 thread to switch.

**Comment by Neilpang** [comment]
if the old api is still working,  we MUST keep it compatible.  otherwise the existing users would panic.
You can make a new one,  eg: `dns_openprovider_rest`

**Pull request closed without merging**
