### PR TITLE
Update dns_cpanel.sh

### PR DESCRIPTION
**Pull request by sm622**
@Neilpang @arnebjarne 
Please check the changes as suggested. It is working fine for me. But I am not a pro for git or Solaris.

### CODE REVIEW

**Comment by Neilpang** [comment]
don't send to master branch.  please send to dev branch instead.

you don't have to be a pro.

**Comment by sm622** [comment]
> don't send to master branch. please send to dev branch instead.
> 
> you don't have to be a pro.

changed to dev

**Comment by Neilpang** [comment]
run the CI checks in your fork:
https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test

**Comment by arnebjarne** [comment]
@sm622 What does this commit solve? I cannot read that from the commit comment.
I cannot approve anything i do not understand :)

**Comment by sm622** [comment]
> @sm622 What does this commit solve? I cannot read that from the commit comment.
> I cannot approve anything i do not understand :)
> 

These changes are already done. Actually Cpanel DNS updates were not working previously. You already solved the issue.


https://github.com/acmesh-official/acme.sh/commit/c485011ed1d714540163013f14418dce937dbac1

**Comment by arnebjarne** [comment]
@sm622 or @Neilpang . Can one of you please close, decline or delete this Pull Request then (I do not have such rights to this PR) ?

**Pull request closed without merging**
