### PR TITLE
Refactoring amcedns api (second try)

### PR DESCRIPTION
**Pull request by 0xFelix**
See https://github.com/acmesh-official/acme.sh/pull/1690

I picked up @dampfklon's patches and adjusted them so ACMEDNS_BASE_URL is saved in domainconf.

Hopefully this can get merged now. :)

### CODE REVIEW

**Comment by 0xFelix** [comment]
Here are the results of the successful DNS GitHub action: https://github.com/0xFelix/acme.sh/actions/runs/333224683

**Comment by 0xFelix** [comment]
https://github.com/0xFelix/acme.sh/runs/1320852829

The successful results for commit https://github.com/0xFelix/acme.sh/commit/23ef7d20e2489ac93962241ef7c15f52c42a975a

**Comment by 0xFelix** [comment]
Is there anything preventing the merge of this? :)

**Comment by 0xFelix** [comment]
@Neilpang Another shy ping

**Comment by melkypie** [comment]
@Neilpang any news on this? Current acme-dns implementation restricts it's use to only one subdomain for which it was built to prevent against.

**Comment by Neilpang** [comment]
moving the credentials to domain conf is a big change.
I'm not sure if its necessary.  cause we have 100+ dns apis to consider.

**Comment by melkypie** [comment]
The problem here is if the acme-dns keeps using account conf we can only assign one subdomain to all domains that will be getting certificates while the actual use for acme-dns is to not use a single subdomain for all of them. As this is a breaking change for people who are already using acme-dns, maybe renaming the hook to acmedns_v2 would be a good idea?

**Comment by Neilpang** [comment]
>> maybe renaming the hook to acmedns_v2 would be a good idea?

no,  we need another unique way for all the dns apis to use.

**Comment by jonmchan** [comment]
I want to confirm this is a breaking change that I only discovered after my website domain expired.

My original config only had `ACMEDNS_UPDATE_URL=`. Adding `ACMEDNS_BASE_URL=` is required now.

**Comment by tonyfinn** [comment]
Also adding that this was breaking for me also.

**Pull request merged**
