### PR TITLE
handle challenge-alias "false"

### PR DESCRIPTION
**Pull request by axelhahn**
allows --challenge-alias (fqdn|false) to enable/ disable dns auth per domain.

./acme.sh/acme.sh --issue \
    -d host1.example.com --challenge-alias false \
    -d extern1.example.net --challenge-alias example.com \
    -d host2.example.com --challenge-alias false \
    -d extern2.example.net --challenge-alias example.com \
    --dns dns_infoblox --staging

### CODE REVIEW

**Review by axelhahn — COMMENTED** [review]
Yep, that's better. Using $NO_VALUE is a clean solution compared to a hard coded string.

**Comment by Neilpang** [comment]
please update the usage here:

https://github.com/acmesh-official/acme.sh/wiki/DNS-alias-mode

**Comment by axelhahn** [comment]
I added a section "Mix dns alias and default dns auth" in https://github.com/acmesh-official/acme.sh/wiki/DNS-alias-mode
But it works only if the new code line was published. Shall we add a "coming soon"?

**Comment by Neilpang** [comment]
Thanks,  I will publish the code soon.

**Pull request merged**
