### PR TITLE
dns.la official acme script

### PR DESCRIPTION
**Pull request by sinostephen**
www.dns.la official acme script

### CODE REVIEW

**Comment by sinostephen** [comment]
> **Welcome** Please make sure you're read our [DNS API Dev Guide](../wiki/DNS-API-Dev-Guide) and [DNS-API-Test](../wiki/DNS-API-Test). Then reply on this message, otherwise, your code will not be reviewed or merged. We look forward to reviewing your Pull request shortly ✨

www.dns.la official acme script . Tested by us already

**Comment by Neilpang** [comment]
请确保 dns test 全部通过先: 

https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test

**Comment by sinostephen** [comment]
action 已经全部测试通过

**Comment by Neilpang** [comment]
这个文档读过了吗

**Comment by Neilpang** [comment]
https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Dev-Guide

**Comment by sinostephen** [comment]
读了，但是英语水平一般，有哪个细节错过了？请指点一下！

**Comment by sinostephen** [comment]
> 这个文档读过了吗

已经挨个，一个个核对过了，并且actions也全部通过

**Pull request merged**
