### PR TITLE
Fixed issue 3239 and 2696 with ISP config 

### PR DESCRIPTION
**Pull request by pssara**
The Client ID was asumed to be the same as the SYS User ID. We now retrieve the correct Client ID.

### CODE REVIEW

**Comment by pssara** [comment]
I manually run shfmt test and there is no change in the output. As for the DNS test, i manually run it several times, however i dont have a public accessible ISPconfig server to run the test from github.

**Comment by MalteHillmann** [comment]
I can confirm that this fix is working with latest stable ISPconfig.

**Review by MalteHillmann — APPROVED** [review]
Works on latest stable ISPconfig.

**Comment by Neilpang** [comment]
can you please fix all the checks:
https://github.com/acmesh-official/acme.sh/pull/3365/checks

**Comment by MalteHillmann** [comment]
> can you please fix all the checks:
> https://github.com/acmesh-official/acme.sh/pull/3365/checks

He can't do that because he don't have an public accessible ISPconfig server. I checked the sourcecode with my ISPconfig server, so I can confirm this code is working, even if the github checks won't work.

**Comment by Neilpang** [comment]
you don't have to expose the server address.  and the checks won't run again.
you just need to make it run once.

**Comment by MalteHillmann** [comment]
> you don't have to expose the server address. and the checks won't run again.
> you just need to make it run once.

Can I do that for @pssara ?

**Comment by Neilpang** [comment]
Yes.

**Comment by MalteHillmann** [comment]
> Yes.

Do I have to do a fork/change, too? Or how can I do that?

**Comment by Neilpang** [comment]
emmm,  good question.

may be you can clone his repo, and enable github actions on your fork.  it will run there.
As long as all the checks pass,  I will merge this pr.

Thanks.

**Comment by MalteHillmann** [comment]
> emmm, good question.
> 
> may be you can clone his repo, and enable github actions on your fork. it will run there.
> As long as all the checks pass, I will merge this pr.
> 
> Thanks.

I've tested this and encountered some problems:
dns_ispconfig.sh uses ISPC_User, ISPC_Password, ISPC_Api and ISPC_Api_Insecure as environment variables and not TokenName1 to TokenNameX so I think DNS.yml will run to an error. (see https://github.com/MalteHillmann/acme.sh/runs/1712652726 )

How to fix that? I've not much knowledge about the acme.sh code.

**Comment by Neilpang** [comment]
TokenName1  is "ISPC_User"
TokenName2 is  "ISPC_Password"
TokenName3 is  "ISPC_Api "
TokenName4 is  "ISPC_Api_Insecure "

**Comment by MalteHillmann** [comment]
> TokenName1 is "ISPC_User"
> TokenName2 is "ISPC_Password"
> TokenName3 is "ISPC_Api "
> TokenName4 is "ISPC_Api_Insecure "

Thank you for clarifying this. I just missed that before.
Please see the test result at https://github.com/MalteHillmann/acme.sh/actions/runs/489571189

**Comment by Neilpang** [comment]
Thank you so much.

I just noticed another issue,  please look at this line:

https://github.com/acmesh-official/acme.sh/blob/b7a3fe05a4d8a9041159b4a773b35003166f0af0/dnsapi/dns_ispconfig.sh#L73

As refer to the guide:  https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Dev-Guide#3-detect-which-part-is-your-root-zone

The fullname may be `example.com`, so, `curZone="${curZone#*.}"` may not work right in this case.

Are any one of you guys interested in fixing this issue?  (Maybe in another PR)

Thanks.

**Comment by pssara** [comment]
i will give it a try when i have some time.

**Pull request merged**
