### PR TITLE
Added DreamHost DNS API

### PR DESCRIPTION
**Pull request by RhinoLance**

### CODE REVIEW

**Comment by Neilpang** [comment]
Please rebase and fix the errors.

**Comment by Neilpang** [comment]
please fix the errors:

https://travis-ci.org/Neilpang/acme.sh/jobs/250144891

**Comment by Neilpang** [comment]
@RhinoLance 
How is going on ?

**Comment by RhinoLance** [comment]
Hi Neil,

I have been away.  I will try to get onto it his week.

Lance

Till next time

Lance Conry

*RhinoSoftware*

+61 (0)40 636 8420
Lance@RhinoSW.com <lance@rhinosw.com>
RhinoSW.com <http://rhinosw.com>

RhinoSpect.com The simplest way to collect information in the field, and
use it in the office

**Pull request closed without merging**
