### PR TITLE
Implement service account key authentication dns_gcloud.sh

### PR DESCRIPTION
**Pull request by acazacu**
A comprehensive description of what this pull request changes can be read here: https://github.com/acmesh-official/acme.sh/issues/3531.

Once merged, the wiki should be updated to reflect the added functionality.

### CODE REVIEW

**Comment by jmcombs** [comment]
Can we please merge this PR into the master?

**Comment by Neilpang** [comment]
Is this change compatible with the existing acme.sh users? I mean the existing certs can renew without any changes?

**Comment by jmcombs** [comment]
> Is this change compatible with the existing acme.sh users? I mean the existing certs can renew without any changes?

So, I actually have the existing `dnsapi_gcloud` implementation working with service account credentials. I figured this out after I posted my comment above so, to me, this PR is moot. 
I am happy to update the documentation on the Wiki for how to use a service account however, I don't think Wiki pages on Github allow me to submit a PR to do so. So, let me know how you'd like the updated instructions for https://github.com/acmesh-official/acme.sh/wiki/dnsapi#49-use-google-cloud-dns-api-to-automatically-issue-cert and I can provide them.

**Comment by typytypytypy** [comment]
@jmcombs would you mind putting some documentation in this issue until they update the wiki?  Would be very helpful :-)

**Comment by typytypytypy** [comment]
@acazacu were you able to find a workaround to get dns_gcloud working with pfsense?

**Comment by jmcombs** [comment]
@typytypytypy I wanted to keep running `acme.sh` in Docker so I created and published a container that runs the Google Cloud SDK and `acme.sh`. It and the instructions on how to use it with service accounts are on [Docker jmcombs/acme.sh-gcloud](https://hub.docker.com/r/jmcombs/acme.sh-gcloud). GitHub repo is https://github.com/jmcombs/acme.sh-gcloud. Those instructions can be used for doing this with local installs of `acme.sh` and `gcloud` SDK. I hope that helps.

**Pull request closed without merging**
