### PR TITLE
Create plex.sh

### PR DESCRIPTION
**Pull request by fergbrain**
Deploy script for use with a local Plex Media Server. Could help resolve Issues #3474, #3893, and #285

### CODE REVIEW

**Comment by fergbrain** [comment]
Updated based on failed shellcheck workflow

**Comment by fergbrain** [comment]
Testing with shellcheck v0.8 doesn't yield any flags for SC2154, however, the workflow still failed when running with shellcheck v0.7. This is a known issue and was [fixed with shellcheck v0.7.2](https://github.com/koalaman/shellcheck/blob/4c186c20b9a5a3a95768d9a609c93df37991c663/CHANGELOG.md#v072---2021-04-19): "SC2154: Variables appearing in -z/-n tests are no longer considered unassigned"

I've disabled checking for SC2154 for now.

Note: you can test with 0.8 by using https://www.shellcheck.net/, just delete the `# shellcheck disable=SC2154` line at the top first.

**Comment by strausmann** [comment]
Hello @fergbrain,

why was this change not merged into [Acme.sh](https://github.com/acmesh-official/acme.sh/) ?

**Comment by fergbrain** [comment]
@strausmann: Oh good question. I'm not sure what happened. I think it might have been user error on my part. I've resubmitted the patch: https://github.com/acmesh-official/acme.sh/pull/6395

**Comment by fergbrain** [comment]
> it would be good if you could customize the restart command using a variable, e.g. to “docker restart ”.

@strausmann Good idea! I put my response over in the new pull request: https://github.com/acmesh-official/acme.sh/pull/6395#issuecomment-2961144840

**Pull request closed without merging**
