### PR TITLE
Improved api compatibility with devices

### PR DESCRIPTION
**Pull request by LJea**
Some operating systems cannot format "%s%N" correctly, and the error result 1692780018%N is generated.  As a result, the url encoding problem occurs

### CODE REVIEW

**Comment by Neilpang** [comment]
改了 dns,  你需要先通过 dns 测试: https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test

**Comment by LJea** [comment]
Whether you can approve this workflow
https://github.com/acmesh-official/acme.sh/actions/runs/5996606671

**Comment by Neilpang** [comment]
https://github.com/LJea/acme.sh/actions/workflows/DNS.yml

dns 测试时在你的repo 中运行的.

Please make sure you're read our [DNS API Dev Guide](https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Dev-Guide) and [DNS-API-Test](https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test).

**Comment by LJea** [comment]
DNS checks have been passed
https://github.com/LJea/acme.sh/actions/runs/6059260853

**Pull request merged**
