### PR TITLE
dns_gd (GoDaddy) Remove complete TXT record instead of value only

### PR DESCRIPTION
**Pull request by awalon**
In addition to DNS records maintenance task "#todo: check if the record takes effect" was implemented by some error handling and validation.

Second try as it seems first CI by GH-actions (#4238) had some timing and timeout issues.

### CODE REVIEW

**Comment by awalon** [comment]
DNS-API-Test was setup but takes a long time caused by long dnssleep times needed for GoDaddy.

**Comment by awalon** [comment]
Adjustment works fine for Debian and OpnSense here, but fails with your docker setup (Ubuntu?), is there something wrong with GH actions? Could you give ne a hint please?
Ex.:
```
2022/08/15 21:53:54 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
2022-08-15T21:53:55Z ERR Failed to serve quic connection error="Unauthorized: Failed to get tunnel" connIndex=0 ip=198.41.200.13
2022-08-15T21:53:55Z ERR Register tunnel error from server side error="Unauthorized: Failed to get tunnel" connIndex=0 ip=198.41.200.13
2022-08-15T21:53:55Z INF Retrying connection in up to 2s seconds connIndex=0 ip=198.41.200.13
```
Btw. there was some successfully executed tests made during last days (https://github.com/acmesh-official/acme.sh/pull/4238), then it was reverted before I had the chance to retry the failed ones.

**Comment by Neilpang** [comment]
I don't understand your PR,  can you explain more?

**Comment by awalon** [comment]
Hello Neilpang, 
sure of course.

Motivations:
* Keep DNS entries clean from processed and no more needed TXT records used for certificate process
* Don't show internally used hosts via public DNS after certificate was created/updated

Before my changes in GoDaddy DNS update process the TXT records was set to an empty string (function "dns_gd_rm").
After my [changes](https://github.com/acmesh-official/acme.sh/pull/4244/commits/5684b7c329ca4be798e63c3180bb3f87ede76823) (lines 54-55, 123-135, 181-182) the processed TXT value will be removed from DNS (delete TXT entry instead of update with "").

During my implementation work "#todo: check if the record takes effect" was implemented as well. After TXT records was created via GoDaddy DNS API an additional API call is used to verify that the new record is really available in GoDaddy administration section (lines 63-81). 

Greets, Ralf

**Pull request merged**
