### PR TITLE
add managed identity support for azure dns

### PR DESCRIPTION
**Pull request by mic-hnk**
> A common challenge for developers is the management of secrets and credentials used to secure communication between different components making up a solution. Managed identities eliminate the need for developers to manage credentials. 

https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview

I think this would be useful. I tested both flows - "old" service principal credentials and "new" managed identity on Azure VM.

### CODE REVIEW

**Comment by mic-hnk** [comment]
@Neilpang is there something more I should do to have CI run?

**Comment by mic-hnk** [comment]
@Neilpang Hi, is there something blocking merging this change?

**Comment by Neilpang** [comment]
can you update the usage here first:
https://github.com/acmesh-official/acme.sh/wiki/dnsapi#37-use-azure-dns

**Comment by mic-hnk** [comment]
> can you update the usage here first: https://github.com/acmesh-official/acme.sh/wiki/dnsapi#37-use-azure-dns

done

**Comment by Neilpang** [comment]
merged, thanks

**Pull request closed without merging**
