### PR TITLE
Add dnsapi for GeoScaling

### PR DESCRIPTION
**Pull request by jinhill**
Add dnsapi  for GeoScaling.
Their smart dns can dynamically based on country/city/network name/uptime of your servers/server loads, see https://www.geoscaling.com

### CODE REVIEW

**Comment by jinhill** [comment]
I always  get errors when pull, it works well in both Ubuntu 20.04 and centos8, would you help to provide error information, thank you!
log:
setp: DNS
Run false
  false
  shell: /bin/bash -e {0}
Error: Process completed with exit code 1.

**Comment by jinhill** [comment]
@Neilpang Would you take a look at the error log?

**Comment by Neilpang** [comment]
read this link please: 
 https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test

**Comment by waldner** [comment]
Hi, why was this removed? Would you accept another PR for this provider?

**Comment by Neilpang** [comment]
@waldner  

yes, you can make another try.

**Pull request closed without merging**
