### PR TITLE
update arvan api script

### PR DESCRIPTION
**Pull request by fvahid**

### CODE REVIEW

**Comment by fvahid** [comment]
Hi ,
would you consider this request
thanks for your advice

**Comment by Neilpang** [comment]
can you elaborate on this change ?

**Comment by fvahid** [comment]
yes sure @Neilpang 

I've found out problem in call arvan api to add and remove txt record . I wan't use arvan script to issue new acme certificate but I've faced error , I think Arvan change API call in own side that cause we still have problem

**Comment by fvahid** [comment]
could you update this issue?

**Comment by fvahid** [comment]
@Neilpang ,
would you please accept this pull request

**Comment by fvahid** [comment]
Guy's please update this issue

**Comment by Neilpang** [comment]
fix the CI checks first: https://github.com/acmesh-official/acme.sh/pull/3338/checks?check_run_id=1651701029

**Comment by fvahid** [comment]
base on this document https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test , I enable action on forked repo and follow instruction all test successfully done on this repo https://github.com/fvahid/acme.sh

**Pull request merged**
