### PR TITLE
Add a deploy hook for AliCDN

### PR DESCRIPTION
**Pull request by WETOOP**
This pull request adds a deploy hook for AliCDN.

### CODE REVIEW

**Comment by Brooooooklyn** [comment]
any update?

**Comment by juukee** [comment]
any update?

**Review by shoyuf — APPROVED** [review]

**Comment by shoyuf** [comment]
@WETOOP  why not merge this?

**Comment by litecy** [comment]
failed to deploy to aliyun cdn with a wild domain eg. *.foo.com, process an error [DomainNotFound]

**Comment by WETOOP** [comment]
> @WETOOP why not merge this?

I'm not the owner. 
I don't know why the owner still not merge this.

**Comment by WETOOP** [comment]
> failed to deploy to aliyun cdn with a wild domain eg. *.foo.com, process an error [DomainNotFound]

Please read the /deploy/README.md in this merge branch. You can use DEPLOY_CDN_Ali_Prefix to specify the prefix when using wildcard domain. You must specify the prefix only a dot(.) for DEPLOY_CDN_Ali_Prefix.

**Comment by PMExtra** [comment]
> failed to deploy to aliyun cdn with a wild domain eg. *.foo.com, process an error [DomainNotFound]

@litecy Try #5205 with `DEPLOY_ALI_CDN_DOMAIN=custom.domain.tld`.

You can also deploy a single wildcard certificate to multiple CDN domains with `DEPLOY_ALI_CDN_DOMAIN=custom1.domain.tld custom2.domain.tld`

**Pull request closed without merging**
