### PR TITLE
Fix due to MyDNS.JP site change

### PR DESCRIPTION
**Pull request by epgdatacapbon**

### CODE REVIEW

**Comment by epgdatacapbon** [comment]
Dear Sir,

I read 'https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test' and set up all variables.
However, DNS check has not been passed. I have no idea.

I set up my own server and confirmed this API works well.
(Previous dns_mydnsjp does not work anymore, so I fixed it.)

**Comment by Neilpang** [comment]
```

[Sun May  2 03:39:42 UTC 2021] You didn't specify mydnsjp api MasterID and Password yet.
[Sun May  2 03:39:42 UTC 2021] Please export as MYDNSJP_MasterID / MYDNSJP_Password and try again.
[Sun May  2 03:39:42 UTC 2021] Error add txt for domain:_acme-challenge.***

```


you must fix it.

**Comment by epgdatacapbon** [comment]
Than you for the comment.

I set my MYDNSJP_MasterID and MYDNSJP_Password in Github actions Secrets, but still get errors.

**Comment by epgdatacapbon** [comment]
Thank you for the comment.
I set all parameters again, and it seems work now.
Please rerun workflow.
Thanks.

**Comment by epgdatacapbon** [comment]
I close the PR to run workflow.

**Comment by msys0843** [comment]
I'm sorry without check this pull request. I raised pull request wihtin own change. I cannot understand why your request was failed.

**Pull request closed without merging**
