### PR TITLE
add support for using a Zone ID

### PR DESCRIPTION
**Pull request by artooro**
Per comments in issue #2398 this pull request is to support using Cloudflare Zone IDs which allows an API token to be restricted to a specific domain which is not possible with the current implementation.

### CODE REVIEW

**Comment by artooro** [comment]
I'll fix the shellcheck issue hopefully tonight.

**Comment by msg7086** [comment]
We were using this version but we saw occasional failures on removing entries.

```
[Wed 19 Feb 2020 05:56:33 AM UTC] Removing DNS records.
[Wed 19 Feb 2020 05:56:33 AM UTC] Removing txt: xxyyzz for domain: _acme-challenge.xxyyzz.example.com
[Wed 19 Feb 2020 05:56:34 AM UTC] Error removing txt for domain:_acme-challenge.xxyyzz.example.com
```

I cannot reproduce this issue reliably. When I enable debug mode and test for a few times it worked. On production it sometimes fails.

Did you hit the same issue?

**Comment by artooro** [comment]
@msg7086 I've had some issues which appeared to be transient cloudflare issues, and that happened before this patch.
In order to get a full understanding we'd have to see debug logs of course.

**Comment by msg7086** [comment]
Thanks. If I manage to get a debug log I'll let you know.

**Pull request merged**
