### PR TITLE
dns_1984.hosting.sh: fix login with valid csrftoken

### PR DESCRIPTION
**Pull request by phedoreanu**
Fixed broken login by adding valid `csrftoken`. 

See [this](https://github.com/acmesh-official/acme.sh/issues/2851#issuecomment-1299361958) for details.

### CODE REVIEW

**Comment by Neilpang** [comment]
https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test

**Comment by phedoreanu** [comment]
Yeah, thanks. Seems the headers aren't set on the POST login request in Github Actions. Locally everything works fine.

Any idea why the headers might not be set?

**Comment by howaboutlollmao** [comment]
Fails on Linux as well, debug logs show the token as empty string (`csrf_token: ''`).

**Comment by phedoreanu** [comment]
The `csrf_token` is set. See https://github.com/phedoreanu/acme.sh/actions/runs/3557572900/jobs/5975667056. 
The headers aren't set, for some reason 😕 

Screenshot 2022-12-07 at 10 31 54

**Comment by phedoreanu** [comment]
@Neilpang domain is validated and certificates issued, but the workflow still fails. Any idea why?

How can I add `--ecc` to the test command?

**Comment by phedoreanu** [comment]
Finally - https://github.com/phedoreanu/acme.sh/actions/runs/5000422959.

@Neilpang please merge 😃

**Comment by phedoreanu** [comment]
It would be great to have it in the next release 🥳

**Comment by phedoreanu** [comment]
Any chance for a review and hopefully a merge, pretty please? 🙄

**Pull request merged**
