### PR TITLE
Fix for (broken) KASAPI by all-inkl.com

### PR DESCRIPTION
**Pull request by Hobby-Student**
Hi,

I'm using the KASAPI by all-inkl.com. Unfortunately the current version is not working anyomore since a few weeks. I tested those modifications and they do work as expected.

This pull request is a complete overhaul in regards of the API calls. It's not using the test form anymore, it now depends on the official API documentation.

If there are any questions, feel free to ask.

Kind regards
Hobby

### CODE REVIEW

**Comment by Hobby-Student** [comment]
github Actions fail and I have no idea why. deployed the fix to several machines over the day and they all work smooth. will try again in a few days.

**Comment by Marco4223** [comment]
Hi Hobby
I checked your implementation and see that you are still using Username and password for every request. 
So this could be caused some problems. So you need to use the session token.
I think we both have the same problem (reported here -> https://github.com/acmesh-official/acme.sh/issues/4215) with the timeouts. The complete code to use the SOAP API with session token can be found here: [[Marco4223/acme.sh -> dns_kas.sh](https://github.com/Marco4223/acme.sh/blob/master/dnsapi/dns_kas.sh)](https://github.com/Marco4223/acme.sh/blob/master/dnsapi/dns_kas.sh)
I'm just waiting for answeres from Nail befor I comit my code. 
Cheers
MarcO

**Comment by Hobby-Student** [comment]
> Hi Hobby I checked your implementation and see that you are still using Username and password for every request. So this could be caused some problems. So you need to use the session token. I think we both have the same problem (reported here -> #4215) with the timeouts. The complete code to use the SOAP API with session token can be found here: [[Marco4223/acme.sh -> dns_kas.sh](https://github.com/Marco4223/acme.sh/blob/master/dnsapi/dns_kas.sh)] I'm just waiting for answeres from Nail befor I comit my code. Cheers MarcO

the documentation states, that one can use either the session token or just user/password on every request. I will try to debug the github actions like @Neilpang described.

**Comment by Hobby-Student** [comment]
> please rebase to the latest dev branch. and define a secret `DEBUG=2` in your repo, it will output more debug info.

did so. Running the Actions is very slow and makes debugging hard. For now it always fails inside "Docker" at centos 7. Sometimes a TXT record gets added but most of the time the requests timeout.

**Comment by Hobby-Student** [comment]
@Neilpang
tried it, but it seems that the github actions won't work atm with the KASAPI. Failures are always curl timeouts. The changes are working in several production environments.
Changed a few things while testing github actions and implemented better error handling.

**Comment by Neilpang** [comment]
merged by https://www.youtube.com/watch?v=d02moVs-ffk&list=PL9K8ksI6u303Jp5oT2CmC-Qu7gIfrb-S1

**Pull request closed without merging**
