### PR TITLE
Anexia CloudDNS Support

### PR DESCRIPTION
**Pull request by ma331**
Wiki updated in https://github.com/acmesh-official/acme.sh/wiki/dnsapi.
bug report created as https://github.com/acmesh-official/acme.sh/issues/3238

### CODE REVIEW

**Comment by ma331** [comment]
added settings according to https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test

**Comment by ma331** [comment]
All checks work, only "DNS / Fail (pull_request)" doesnt. But according to some comments from other pull requests there are some issues with that.

**Comment by Neilpang** [comment]
enable github actions for your fork:
https://github.com/ma331/acme.sh/actions

And the DNS workflow will run there.

**Comment by ma331** [comment]
Shame on my ... only enabled the actions in settings, not in action menu.

**Comment by ma331** [comment]
I can see in our dns logs that the TXT record is created and removed properly.
DNS Check still fails with no real error msg.

**Comment by ma331** [comment]
Seems like a problem with alpine container. Will try run again later.

`Step 1/2 : FROM alpine:latest
latest: Pulling from library/alpine
188c0c94c7c5: Pulling fs layer
188c0c94c7c5: Verifying Checksum
188c0c94c7c5: Download complete
188c0c94c7c5: Pull complete
Digest: sha256:c0e9560cda118f9ec63ddefb4a173a2b2a0347082d7dff7dc14272e7841a5b5a
Status: Downloaded newer image for alpine:latest
 ---> d6e46aa2470d
Step 2/2 : RUN apk update -f  && apk --no-cache add -f openssl curl socat
 ---> Running in c82f2309b910
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
v3.12.1-10-ge724957f3e [http://dl-cdn.alpinelinux.org/alpine/v3.12/main]
v3.12.1-9-g3c7f8a65fa [http://dl-cdn.alpinelinux.org/alpine/v3.12/community]
OK: 12744 distinct packages available
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/9) Installing ca-certificates (20191127-r4)
(2/9) Installing nghttp2-libs (1.41.0-r0)
(3/9) Installing libcurl (7.69.1-r1)
(4/9) Installing curl (7.69.1-r1)
(5/9) Installing openssl (1.1.1g-r0)
(6/9) Installing ncurses-terminfo-base (6.2_p20200523-r0)
(7/9) Installing ncurses-libs (6.2_p20200523-r0)
(8/9) Installing readline (8.0.4-r0)
(9/9) Installing socat (1.7.3.4-r0)
Executing busybox-1.31.1-r19.trigger
Executing ca-certificates-20191127-r4.trigger
OK: 9 MiB in 23 packages
Removing intermediate container c82f2309b910
 ---> 47ab903dae8f
Successfully built 47ab903dae8f
Successfully tagged myalpine:latest
alpine:latest [FAIL]
[Thu Oct 29 13:16:15 UTC 2020] Failed: alpine:latest
Error: Process completed with exit code 1.`

**Pull request merged**
