### PR TITLE
Updates dns_cyon txt_body and adds validation

### PR DESCRIPTION
**Pull request by InteractiveNinja**
Hello!

I recently attempted to update my domains certificate via acme.sh, but encountered issues with the txt validation.
After some debugging, I found at that the form body had changed a little.

### Changes
`zone` ➡️ `name`
`value` ➡️  `dnscontent`

I also added a validation for the response being returned after the update, in hopes that it will actually bail if the update fails.
I didn't try it, but I think it should work.

Thanks for this great tool, and also thanks for maintaining support for cyon domains 👍

### CODE REVIEW

**Comment by mikch06** [comment]
That's the issue!
Thx a lot!

**Comment by dedors** [comment]
Waiting for this too, hope will get merged soon.
In the meantime, it's possible to add the TXT record manually.

**Comment by mike4054** [comment]
I'm waiting for that update too but I see this is closed now. Any chance that this will make it to the release somewhen?

**Comment by StringWriter** [comment]
I had to make following changes to make it working:

diff dns_cyon.sh dns_cyon.sh0
307c307
<   _egrep_o '"status":[a-z**A-Z**0-9]*' | cut -d : -f 2
>   _egrep_o '"status":[a-zA-z0-9]*' | cut -d : -f 2
311c311
<   _egrep_o '"valid":[a-z**A-Z**0-9]*' | cut -d : -f 2
>   _egrep_o '"valid":[a-zA-z0-9]*' | cut -d : -f 2
319c319
<   _egrep_o '"authenticated":[a-z**A-Z**0-9]*' | cut -d : -f 2
>   _egrep_o '"authenticated":[a-zA-z0-9]*' | cut -d : -f 2

**Pull request closed without merging**
