### PR TITLE
Plesk XMLAPI Compatibility with all Plesk editions

### PR DESCRIPTION
**Pull request by lufi42**
Fixing the way of Plesk API calls to fetch all domains. This implementation of the Plesk API is compatible with all Plesk editions.

This implementation of the Plesk API will add support for Plesk web admin edition and will now discover all domains managed by the specific plesk instance.

The existing implementation of the Plesk API uses the customer API. This results in two problems:
1. The current API call only fetches the domains of resellers/customers and not the domains that are managed by  administrative users.

compare:
https://docs.plesk.com/en-US/obsidian/api-rpc/about-xml-api/reference/managing-customer-accounts/retrieving-the-list-of-customer%E2%80%99s-domains.75309/
https://docs.plesk.com/en-US/obsidian/api-rpc/about-xml-api/reference/managing-plesk-server/getting-server-information/response-packet-structure-and-samples/list-of-domains.75294/

2. The customer API is only available in the pro/admin editions. But the most common license on VPS/Dedicated Servers is the web host edition. See: https://www.plesk.com/editions/

The correct way to get all domains in all Plesk editions is to use the Sites (Domains) API:
https://docs.plesk.com/en-US/obsidian/api-rpc/about-xml-api/reference/managing-sites-domains/getting-information-about-sites.66583/

### CODE REVIEW

**Comment by Neilpang** [comment]
please fix the dns ci test in your fork:
https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test

**Comment by Neilpang** [comment]
please rerun your tests,  sometimes there could be some temp error from the CA.

**Comment by lufi42** [comment]
@Neilpang I think it's time to give up. My code is working. I spent hours to unterstand how to pass the tests. But the tests are failing in step 1xxx and I think that the reason is not this DNS plugin.

The newest funny thing is this:
```
[Sat Jul 16 21:17:59 UTC 20[22](https://github.com/lufi42/acme.sh/runs/7373185859?check_suite_focus=true#step:5:23)] Log_Out='logs/ubuntu-latest.out'
./rundocker.sh: line 326: logs/ubuntu-latest.out: No such file or directory
[Sat Jul 16 21:17:59 UTC 2022] code='1'
cat: logs/ubuntu-latest.out: No such file or directory
ubuntu:latest [FAIL]
```

**Comment by Neilpang** [comment]
sorry, the newest error was brought in yesterday by my changes.  It should be fixed now.
please rerun your tests.

**Comment by Neilpang** [comment]
image

**Comment by lufi42** [comment]
The tests are all green now. @Neilpang can you please review.

**Pull request merged**
