### PR TITLE
Add DNS "API" support for Strato.de

### PR DESCRIPTION
**Pull request by Devirex**
Strato does not provide a REST api for changing DNS records, but it is possible to do so with their web interface.
This is an sh approach to automate this process.
Contents of "dns_strato.sh" :

- use wget for login in with account number an password
- saving cookie to local file
- getting existing values of the TXT section in the portal
- change _acme-challange TXT to generated value
- post changes to the webinterface
- reporting successful change
- removing saved cookies.txt file
dns_strato

### CODE REVIEW

**Comment by Devirex** [comment]
> **Welcome** Please make sure you're read our [DNS API Dev Guide](../wiki/DNS-API-Dev-Guide) and [DNS-API-Test](../wiki/DNS-API-Test). Then reply on this message, otherwise, your code will not be reviewed or merged. We look forward to reviewing your Pull request shortly ✨

Did so but this is not a REST Api

**Comment by Neilpang** [comment]
https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Dev-Guide
https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test

why do I have to paste these links by my hand everytime?

**Comment by Devirex** [comment]
> https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Dev-Guide https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test
> 
> why do I have to paste these links by my hand everytime?

Maybe because you didn‘t read what I wrote? It’s just not possible to do the cookie and data handling of a non rest based page with just put and get requests. So deny it or accept it, but the next time you should clearly point out your problems to someone who just want to contribute to the project.

**Comment by Neilpang** [comment]
If you ever read one of the links, you will know there are a lot to modify first.
eg:
1. the  file shebang,
2. don't use `wget`,  you should use "_get()" or "_post()"
3. don't use `grep -E`
4. .......


if you are using wget,  I don't know why there is a problem to handle cookies, we have already a lot of dns api handlers using cookies.

**Pull request closed without merging**
