### PR TITLE
Add DNS API plugin for Technitium DNS Server

### PR DESCRIPTION
**Pull request by Djelibeybi**
Supports ACMEv2 wildcard certificates.

Signed-off-by: Avi Miller <me@dje.li>

### CODE REVIEW

**Comment by Djelibeybi** [comment]
> Then reply on this message, otherwise, your code will not be reviewed or merged.

DNS workflow run: https://github.com/Djelibeybi/acme.sh/actions/runs/4149762547

**Comment by Neilpang** [comment]
please rebase to the latest code first, and retry the actions again.

**Comment by Djelibeybi** [comment]
Rebased and the updated DNS action is running here: https://github.com/Djelibeybi/acme.sh/actions/runs/4151134119

**Comment by Djelibeybi** [comment]
Closing because the Lexicon DNS API plugin works fine with Technitium.

**Pull request closed without merging**
