### PR TITLE
Refact ssh hook to use deploy config, support scp and support specifying port

### PR DESCRIPTION
**Pull request by PMExtra**
The work is based on #3674

### CODE REVIEW

**Comment by PMExtra** [comment]
TODO: Update wiki docs after this feature released.

**Comment by PMExtra** [comment]
@Neilpang Please take a look.

**Comment by PMExtra** [comment]
@Neilpang Please let me know if there is any problem that blocked the PR.

**Comment by Neilpang** [comment]
sure,  I will soon.

**Pull request merged**
