### PR TITLE
Add Gotify notification

### PR DESCRIPTION
**Pull request by victor-rds**
Requires:
- Gotify server URL (GOTIFY_URL)
- Application Token (GOTIFY_TOKEN)
Optional:
- Message priority (GOTIFY_PRIORITY)

### CODE REVIEW

**Comment by Neilpang** [comment]
can you please update the usage here:
https://github.com/acmesh-official/acme.sh/wiki/deployhooks

**Comment by victor-rds** [comment]
> can you please update the usage here: https://github.com/acmesh-official/acme.sh/wiki/deployhooks

You mean https://github.com/acmesh-official/acme.sh/wiki/notify?

**Comment by Neilpang** [comment]
yes,

**Comment by cerealconyogurt** [comment]
Hi there!, is there any update about how to get Gotify works with acme.sh?

**Comment by Neilpang** [comment]
read the usage from the source code:
https://github.com/acmesh-official/acme.sh/blob/master/notify/gotify.sh#L5

**Comment by cerealconyogurt** [comment]
> read the usage from the source code: https://github.com/acmesh-official/acme.sh/blob/master/notify/gotify.sh#L5

Thanks. It was easy to follow the source code

**Pull request merged**
