### PR TITLE
Fix MIAB dns create TXT record format

### PR DESCRIPTION
**Pull request by lifeboy**

### CODE REVIEW

**Comment by lifeboy** [comment]
Ok, the change has been tested and is working.  Anything else that I need
to do to get the change merged?

**Comment by Neilpang** [comment]
https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test

**Comment by lifeboy** [comment]
The change now has passed all the test which would run...   I presume the skipped tests are intentional?

**Comment by lifeboy** [comment]
@Neilpang, do I just wait now?

**Pull request merged**
