### PR TITLE
Fixes #3645, sed errors in dns_linode_v4.sh

### LINKED ISSUE #3645: Getting sed error using dns_linode_v4 on macOS/Ubuntu: RE error: invalid repetition count(s)
Steps to reproduce
------------------

I'm on macOS Catalina 10.15.7. Following the instructions from:

  https://github.com/acmesh-official/acme.sh/wiki/dnsapi#14-use-linode-domain-api

```
export LINODE_V4_API_KEY="<redacted>"
acme.sh --staging --issue --dns dns_linode_v4 --dnssleep 300 -d 'yurt.dribin.net'  --debug 2
```

I see two `sed` errors:

```
...
[Wed Aug  4 23:54:00 CDT 2021] Adding txt value: <redacted> for domain:  _acme-challenge.yurt.dribin.net
[Wed Aug  4 23:54:00 CDT 2021] Using Linode
sed: 1: "s/.*\(\{.*"domain": *"y ...": RE error: invalid repetition count(s)
[Wed Aug  4 23:54:01 CDT 2021] Domain resource successfully added.
[Wed Aug  4 23:54:01 CDT 2021] The txt record is added: Success.
[Wed Aug  4 23:54:01 CDT 2021] Sleep 300 seconds for the txt records to take effect
[Wed Aug  4 23:59:04 CDT 2021] Verifying: yurt.dribin.net
[Wed Aug  4 23:59:04 CDT 2021] Pending, The CA is processing your order, please just wait. (1/30)
[Wed Aug  4 23:59:06 CDT 2021] Success
[Wed Aug  4 23:59:07 CDT 2021] Removing DNS records.
[Wed Aug  4 23:59:07 CDT 2021] Removing txt: <redacted> for domain: _acme-challenge.yurt.dribin.net
[Wed Aug  4 23:59:07 CDT 2021] Using Linode
sed: 1: "s/.*\(\{.*"domain": *"y ...": RE error: invalid repetition count(s)
[Wed Aug  4 23:59:08 CDT 2021] Domain resource successfully deleted.
[Wed Aug  4 23:59:08 CDT 2021] Removed: Success
...
```

Debug log
-----------------

```
acme.sh --staging --issue --dns dns_linode_v4 --dnssleep 300 -d 'yurt.dribin.net'  --debug 2
[Wed Aug  4 23:46:45 CDT 2021] Lets find script dir.
[Wed Aug  4 23:46:45 CDT 2021] _SCRIPT_='/Users/dave/Scratch/acme.sh/acme.sh'
[Wed Aug  4 23:46:45 CDT 2021] _script='/Users/dave/Scratch/acme.sh/acme.sh'
[Wed Aug  4 23:46:45 CDT 2021] _script_home='/Users/dave/Scratch/acme.sh'
[Wed Aug  4 23:46:45 CDT 2021] Using config home:/Users/dave/Scratch/acme.sh
[Wed Aug  4 23:46:45 CDT 2021] LE_WORKING_DIR='/Users/dave/Scratch/acme.sh'
https://github.com/acmesh-official/acme.sh
v3.0.1
...
[Wed Aug  4 23:46:49 CDT 2021] Using Linode
...
[Wed Aug  4 23:46:49 CDT 2021] _CURL='curl --silent --dump-header /Users/dave/Scratch/acme.sh/http.header  -L  --trace-ascii /var/folders/74/r34bgh6d35xgnv_4r1pnb75h0000gn/T/tmp.kM3Z2rAw  -g '
* Closing connection 0
[Wed Aug  4 23:46:50 CDT 2021] ret='0'
[Wed Aug  4 23:46:50 CDT 2021] _hcode='0'
[Wed Aug  4 23:46:50 CDT 2021] response='{"data": [{"id": 348530, "type": "master", "domain": "dribin.net", "tags": [], "group": "", "status": "active", "description": "", "soa_email": "<redacted>", "retry_sec": 0, "master_ips": [], "axfr_ips": [], "expire_sec": 0, "refresh_sec": 300, "ttl_sec": 300, "created": "2012-08-05T15:41:40", "updated": "2021-08-05T04:45:53"}], "page": 1, "pages": 1, "results": 1}'
[Wed Aug  4 23:46:50 CDT 2021] h='yurt.dribin.net'
sed: 1: "s/.*\(\{.*"domain": *"y ...": RE error: invalid repetition count(s)
[Wed Aug  4 23:46:50 CDT 2021] h='dribin.net'
[Wed Aug  4 23:46:50 CDT 2021] _domain_id='348530'
[Wed Aug  4 23:46:50 CDT 2021] _sub_domain='_acme-challenge.yurt'
[Wed Aug  4 23:46:50 CDT 2021] _domain='dribin.net'
...
```

### PR DESCRIPTION
**Pull request by ddribin**
Use "{" instead of "\{".

### CODE REVIEW

**Comment by ddribin** [comment]
I spend at least an hour trying to get the Actions to pass, but `TokenName1 = TokenValue1` was never getting set as an environment variable, and I could not set an Linode API key from a secret.

**Comment by Neilpang** [comment]
please set up and make the CI pass.

**Comment by ddribin** [comment]
As I mentioned above, I could not get it to work, following this link:

  https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test

I get this error:

```
[Sat Aug  7 05:33:43 UTC 2021] You didn't specify the Linode v4 API key yet.
```

Even though I did set:

```
TokenName1 = LINODE_V4_API_KEY
TokenValue1 = <my-api-key>
```

@Neilpang, can you help me figure out why? I have not used GitHub Actions very much.

**Comment by Neilpang** [comment]
no, I don't know why.  it should be easy.

**Comment by ddribin** [comment]
I think a recent change in `acmetest` is causing Linode in Docker not to work. See https://github.com/acmesh-official/acmetest/commit/8af6bcf45b81602818a21e1725520c4712c70dc0

**Comment by Neilpang** [comment]
Sorry,  it's fixed now.

please rebase and try again.

Thanks.

**Comment by ddribin** [comment]
The straight `dev` branch failed two tests, `DNS` and `Linux`:

Screen Shot 2021-08-10 at 12 28 30 AM

But my commit failed three, `DNS`, `Linux`, and `Ubunutu`:

Screen Shot 2021-08-10 at 12 28 39 AM

Looking at the logs it says:

```
Ubuntu (ZeroSSL.com, ZeroSSL ECC Domain Secure Site CA, ZeroSSL RSA Domain Secure Site CA, github...
The job was canceled because "LetsEncrypt_org_test" failed.
```

Screen Shot 2021-08-10 at 12 31 15 AM

@Neilpang: Seems unrelated to my change, no?

**Comment by Neilpang** [comment]
re-run it.

**Comment by ddribin** [comment]
Failed again:

```
/home/runner/.acme.sh/acme.sh --revoke -d obtaining-guitars-pick-beautiful.trycloudflare.com [PASS]
124
------------------------------------------
125
Progress: 10/0/19
126
==Running le_test_standandalone_listen_v6_v2 please wait
127
Skipped by TEST_IPV6
128
------------------------------------------
129
Progress: 11/0/19
130
==Running le_test_standandalone_deactivate_v2 please wait
131
 [FAIL] 
132
Run Failed
133
/home/runner/.acme.sh/acme.sh  --server "ZeroSSL.com"  --issue -d obtaining-guitars-pick-beautiful.trycloudflare.com --standalone --certpath '/home/runner/work/acme.sh/acmetest/certs/domain.cer' --keypath '/home/runner/work/acme.sh/acmetest/certs/domain.key'  --capath '/home/runner/work/acme.sh/acmetest/certs/ca.cer'  --reloadcmd 'echo this is reload'  --fullchainpath  '/home/runner/work/acme.sh/acmetest/certs/full.cer'------------------------------------------
134
==Running le_test_standandalone_deactivate_v2 please wait
135
```

Should I upload the whole log file?

**Comment by ddribin** [comment]
Attached a log archive of the Ubuntu. I'm afraid I don't know what's going on, so you'll have to accept/deny this PR as-is, unless you can figure out the CI issues. All I know is this solves the problem for me. Solaris did pass in CI, which is good since Solaris is the only reason the `_egrep_o()` exists.

[logs_32.zip](https://github.com/acmesh-official/acme.sh/files/6965873/logs_32.zip)

**Comment by Neilpang** [comment]
Just click the "Rerun" button on the CI jobs to run your tests again,
it sometimes fails.

**Comment by ddribin** [comment]
Looks like Ubuntu finally passed. @Neilpang: Is there anything else you're looking for, in order to merge?

**Comment by Neilpang** [comment]
please rebase and check the tests again.

**Comment by ddribin** [comment]
It's already rebased on current `dev` ?

```
* b17acf1 - (HEAD -> sed-error-3645) Fixes #3645, sed errors in dns_linode_v4.sh (4 weeks ago) <Dave Dribin>
* 72e3f33 - (dev) fix docker test (4 weeks ago) <neilpang>
```

**Comment by ddribin** [comment]
My Linode key had expired, and I needed to rebase to `dev`. I've updated everything, and it It all works locally. Yet the the DNS API Test action still fails https://github.com/ddribin/acme.sh/actions/runs/1408717835

I cannot figure out why it's failing. I've spent many hours trying to get this DNS API Test action passing for a straightforward two line change. Unfortunately, I cannot spend any more time in this PR. Hopefully you can take it from here.

**Pull request closed without merging**
