### PR TITLE
Update deploy script for gcore

### PR DESCRIPTION
**Pull request by DreamOfIce**
Gcore has change their api domain and format of authorization header recently.

Fix: https://github.com/acmesh-official/acme.sh/issues/4460

### CODE REVIEW

**Comment by Neilpang** [comment]
https://github.com/DreamOfIce/acme.sh/actions/runs/3947576400/jobs/6756566474

**Comment by DreamOfIce** [comment]
> https://github.com/DreamOfIce/acme.sh/actions/runs/3947576400/jobs/6756566474
However, I didn't change the dnsapi, this is just a sync fork operation from upstream

**Comment by Neilpang** [comment]
任何对 dnsapi 的改动, 都必须通过这个测试.

**Comment by DreamOfIce** [comment]
> 任何对 dnsapi 的改动, 都必须通过这个测试.

问题是没改过😅

**Comment by Neilpang** [comment]
那是我看错了, 因为最近有人提交gcore的api改动.

**Pull request merged**
