### PR TITLE
Googledomains api

### PR DESCRIPTION
**Pull request by CruzMarcio**
Adding support for Google Domains managed ACME:
https://domains.google.com/registrar/
https://developers.google.com/domains/acme-dns/reference/rest

### CODE REVIEW

**Comment by CruzMarcio** [comment]
> 

Added the file dns_googledomains and all tests are passing.

**Comment by CruzMarcio** [comment]
> **Welcome** Please make sure you're read our [DNS API Dev Guide](../wiki/DNS-API-Dev-Guide) and [DNS-API-Test](../wiki/DNS-API-Test). Then reply on this message, otherwise, your code will not be reviewed or merged. We look forward to reviewing your Pull request shortly ✨

Added the file dns_googledomains and all tests are passing.

**Comment by z3lb** [comment]
This would be a much needed addition, thank you!

**Comment by vg** [comment]
A different upstream PR for Google Domains has been accepted - #4542 
This PR is therefore redundant.

**Pull request closed without merging**
