### PR TITLE
Akamai Edge DNS DNSAPI Support

### PR DESCRIPTION
**Pull request by edglynes**
Added ./dnsapi/dns_edgedns.sh to support Akamai EdgeDNS. 

Tested on RHEL 7 and neilpang docker image. Ran: acme.sh --staging --issue --dns dns_edgedns -d edgedns.zone -d *.edgedns.zone

Once merged to master, I'll update https://github.com/acmesh-official/acme.sh/wiki/dnsapi

Thx.

### CODE REVIEW

**Comment by edglynes** [comment]
@Neilpang Hi. Can I get an ETA on approval and merge? Thx.

**Comment by Neilpang** [comment]
please update the usage first: https://github.com/acmesh-official/acme.sh/wiki/dnsapi

**Comment by edglynes** [comment]
done, https://github.com/acmesh-official/acme.sh/wiki/dnsapi#116-use-akamai-edge-dns-api

**Comment by edglynes** [comment]
@Neilpang Hi. Wiki updated. Any other review comments? If not, ready to go? Thank you.

**Comment by Neilpang** [comment]
I'm  creating a new CI Action to test dns api. It will be ready soon.

**Comment by Neilpang** [comment]
can you please rebase to latest `dev` branch, and check the CI for the workflow `DNS`?
https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test

**Comment by edglynes** [comment]
@Neilpang I rebased and pushed. not sure how interpet results, https://github.com/acmesh-official/acme.sh/runs/1102890247?check_suite_focus=true

**Comment by Neilpang** [comment]
please read this doc: https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test

**Comment by Neilpang** [comment]
please update to latest dev code

**Pull request closed without merging**
