### PR TITLE
Add Nanelo DNS support

### PR DESCRIPTION
**Pull request by AnTheMaker**
Hi there! I've added support for [Nanelo DNS](https://nanelo.com) via the official Naneo API.

### CODE REVIEW

**Comment by AnTheMaker** [comment]
I've created an Issue to report bugs to: #4519

**Comment by AnTheMaker** [comment]
And here's the successful DNS-Test CI run: https://github.com/AnTheMaker/acme.sh/actions/runs/4257690568

**Comment by Neilpang** [comment]
add the usage here:  https://github.com/acmesh-official/acme.sh/wiki/dnsapi2

**Comment by AnTheMaker** [comment]
@Neilpang Done!

**Comment by AnTheMaker** [comment]
Thanks a lot for merging, @Neilpang! Appreciate it!
When is the next release expected approximately?

**Comment by Neilpang** [comment]
It's merged in the master branch now.

you can upgrade to use the latest master.

The next release will be in a couple of weeks.

**Pull request merged**
