### PR TITLE
acme.sh extention for kapper.net DNS Panel APIv1.1

### PR DESCRIPTION
**Pull request by kappernet**
acme.sh extention for kapper.net DNS Panel APIv1.1

### CODE REVIEW

**Comment by Fabian-Gruenbichler** [comment]
tested, works :+1:

**Comment by Neilpang** [comment]
please merge the latest code and fix the readme files.

**Comment by kappernet** [comment]
Hi,
it’s my first time working with github, so please excuse the possible problems i cause.

I updated
README.md
dnsapi/README.md
dnsapi/dns_kappernet.sh
thx

Michael

Von: neil [mailto:notifications@github.com]
Gesendet: Dienstag, 19. Dezember 2017 15:23
An: Neilpang/acme.sh <acme.sh@noreply.github.com>
Cc: Michael Mülleder <mm@kapper.net>; Author <author@noreply.github.com>
Betreff: Re: [Neilpang/acme.sh] acme.sh extention for kapper.net DNS Panel APIv1.1 (#1102)


please merge the latest code and fix the readme files.

**Comment by kappernet** [comment]
hi, could you be so kind to tell me what the problem is with our script?
line# etc?
thx

**Pull request closed without merging**
