### PR TITLE
[dns_acmedns] Handle many domain cert with many accounts

### PR DESCRIPTION
**Pull request by gaby64**
My solution is to use dynamic variables and append the domain, with the dot replaced by an underscore, to the variable; so you can export a set [username, password, subdomain] for each domain.

### CODE REVIEW

**Comment by gaby64** [comment]
I learned some shell scripting like 3 days ago, I wont be able to rewrite it to be posix compliant.

**Comment by LoganDark** [comment]
This is terrifying

**Comment by gaby64** [comment]
> This is terrifying

What is terrifying? I have it working well for me.

**Comment by LoganDark** [comment]
Just the extremely long chain of `sed`, `tr`, and `awk` commands. Never said it doesn't *work*, but...

**Comment by gaby64** [comment]
> Just the extremely long chain of `sed`, `tr`, and `awk` commands. Never said it doesn't _work_, but...

I didnt write that part: https://www.reddit.com/r/learnprogramming/comments/7sdcdl/comment/dt45446/

**Comment by gaby64** [comment]
would be nice if this could be merged

**Comment by gaby64** [comment]
closed but no reason given, there many looking for a solution like this

#4221

**Comment by maddes-b** [comment]
I wrote my own acme-dns-client that works with acme.sh and certbot with multiple domains in a single certificate.
The script uses Python, so it does not fully fit the acme.sh approach of "shell only".
Please have a look here: https://github.com/maddes-b/acme-dns-client-2
Feedback welcome.

**Pull request closed without merging**
