### PR TITLE
add huaweicloud iam sub-account support

### PR DESCRIPTION
**Pull request by gclm**

### CODE REVIEW

**Comment by gclm** [comment]
test:  acme.sh --issue --dns dns_huaweicloud -d  xxx.com  --test --debug 1

**Comment by xzycn** [comment]
Hi, this is a necessary feature，can we add this？

**Comment by Neilpang** [comment]
@xzycn   Yes,  please  send a new PR

**Comment by xzycn** [comment]
@Neilpang Dose this PR cannot work？Why assigned a label named **rev** and what's that mean？

**Pull request closed without merging**
