### PR TITLE
Update dynv6 dns api to allow custom domains

### PR DESCRIPTION
**Pull request by StefanAbl**
Dynv6 recently updated their service to allow you to use custom domains. So I updated this script as well.  
However it seems like it is still not possible to create wild card certificates using their ssh api. Because there cannot be two txt records with the same name but different data.

### CODE REVIEW

**Comment by StefanAbl** [comment]
With recent changes to the dynv6 service it is now also possible to get a Wildcard certificate from LE. This has been requested in the [issue](https://github.com/acmesh-official/acme.sh/issues/2702) to the API.  
My recent [commits](https://github.com/acmesh-official/acme.sh/pull/2973/commits/f5411ac9ab9f40b0501d99132a561605a9e8d714) also make it possible to use the HTTP API, which is faster and more reliable and does not need SSH.   
If there is anything preventing this from getting merged please let me know.

**Comment by Neilpang** [comment]
please rebase the code and resolve conflicts first.

**Comment by StefanAbl** [comment]
All right I did a rebase and all conflicts seem to be resolved, however the LetsEncrypt test is failing with 
`cd ../acmetest && sudo TEST_LOCAL="$TEST_LOCAL" NGROK_TOKEN="$NGROK_TOKEN" ./letest.sh
  shell: /bin/bash -e {0}
  env:
    NGROK_TOKEN: 
    TEST_LOCAL: 1
The TestingDomain or TestingAltDomains is not specified, see: https://github.com/acmesh-official/acmetest
You can also specify NGROK_TOKEN to test automatically, see: https://github.com/acmesh-official/acmetest
##[error]Process completed with exit code 1.
`
Is there something I need to specify for this to work? Nothing was mentioned in the [DNS API Dev Guide](https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Dev-Guide)

**Comment by Neilpang** [comment]
please rebase code again, the error should be fixed.

**Comment by StefanAbl** [comment]
Thanks that did it. I hope it can be merged now.  
I will also update the [dnsapi wiki](https://github.com/acmesh-official/acme.sh/wiki/dnsapi#97-use-dynv6-api-to-automatically-issue-a-cert).

**Comment by StefanAbl** [comment]
@Neilpang sorry to bump this again, but I'd like to ask if there is anything else keeping this from being merged?

**Pull request merged**
