### PR TITLE
Allow optional "NEW" in CSR header and footer

### PR DESCRIPTION
**Pull request by pearj**
When generating a CSR in Windows it seems to create a CSR header that looks like `-----BEGIN NEW CERTIFICATE REQUEST-----`, but the addition of `NEW` breaks the parsing of the CSR. Making `NEW ` optional fixes the problem.

Apparently [certbot](https://community.letsencrypt.org/t/error-parsing-certificate-request-resolved/40039/6) is tolerant of both forms.

I tested this locally with grep, and it matches both with and without `NEW`.

### CODE REVIEW

**Comment by Neilpang** [comment]
please rebase to the latest dev branch.

**Comment by pearj** [comment]
Hi @Neilpang I've rebased onto the latest dev branch

**Comment by Neilpang** [comment]
It seems your fix is not working in solaris:

```
[Monday, December 13, 2021 at 11:13:58 PM UTC] original='{
  "type": "urn:ietf:params:acme:error:malformed",
  "detail": "Error parsing certificate request: asn1: syntax error: sequence truncated",
  "status": 400
}'
```

**Comment by pearj** [comment]
> It seems your fix is not working in solaris:

It should be working now, I downloaded a solaris vm and found a syntax that worked for solaris and everything else.

The ZeroSSL checks looks like it was a transient failure. I re-ran the tests on my fork and they all passed.

**Comment by pearj** [comment]
I did an amend with no changes in the hope of triggering the checks to run again, but it looks like it needs you to approve them.

**Comment by Neilpang** [comment]
can you please rerun the failed tests ?

**Comment by pearj** [comment]
> can you please rerun the failed tests ?

I re-ran the failed tests on my fork and they have all passed now.

**Pull request merged**
