### PR TITLE
Add BookMyName API support

### LINKED ISSUE #1740: bookmyname dns api integration in acme.sh
Hi,
I have some domain-name with bookmyname registar.
They have an api : https://api.doc.bookmyname.com/
But not handled by acme.sh today : https://github.com/Neilpang/acme.sh#7-automatic-dns-api-integration

if somebody publish the script, i will be happy.
if not, some help about how to write it myself is welcome.

Thanks for acme.sh !

### PR DESCRIPTION
**Pull request by alaunay**
Hello,

This adds BookMyName (https://www.bookmyname.com/) API support to acme.sh.

API documentation is here:
https://fr.faqs.bookmyname.com/frfaqs/dyndns
(in french, near the end)

It fixes #1740 .

Thanks,
Arnaud.

### CODE REVIEW

**Comment by alaunay** [comment]
I added the secrets and enabled the actions on my repository, but it still fails... Not very clear where though... If you have any hint, I'm interested (the stuff works anyway).

**Comment by Neilpang** [comment]
I checked your Actions log. it seems ok.
The failure was caused by workflow errors.  I'm fixing it. Just leave it.

But please read and finish the guide here:
https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Dev-Guide

**Comment by alaunay** [comment]
Hi Neil,

Thanks ! I did miss the "create issue" step, it's fixed: #3209 

About the doc, I was wondering if I have to add it now, or if/when the api is added to the dev code ?

Thanks !

**Comment by Neilpang** [comment]
>> About the doc, I was wondering if I have to add it now, or if/when the api is added to the dev code ?

Yes,  please add the doc now.  

please also rebase the latest dev code and run the actions now.

**Comment by alaunay** [comment]
Doc done. I tried the rebase (probably wrongly...), and the DNS action still fails :(

**Comment by Neilpang** [comment]
```
[Fri Oct  9 15:33:36 UTC 2020] ***:Verify error:DNS problem: NXDOMAIN looking up TXT for _acme-challenge.*** - check that a DNS record exists for this domain
```

**Comment by alaunay** [comment]
I don't get it, sorry. It works just fine locally, no idea why it doesn't on github. I redid all the secrets, still the same result...

Running locally, with some bits "masked":

[acme.log](https://github.com/acmesh-official/acme.sh/files/5358788/acme.log)

Arnaud.

**Comment by alaunay** [comment]
Hello, checks rerun. DNS fails, apparently docker isn't happy.

**Comment by Neilpang** [comment]
rebase the latest dev code and try again

**Comment by alaunay** [comment]
> rebase the latest dev code and try again

I'm not sure what I should do. My repo is already sync to the acme repo ?

Date:   Thu Jun 15 14:13:58 2023 +0200
    Merge branch 'acmesh-official:master' into master

And there's no new commits, so I don't have the possibility to merge (rebase ?) again... ?

**Comment by Neilpang** [comment]
you must fix your ci tests:
https://github.com/cusae/acme.sh/actions/runs/5278904617

it's not passing now.

**Comment by Neustradamus** [comment]
Replaces:
- https://github.com/acmesh-official/acme.sh/pull/3208

**Comment by Neustradamus** [comment]
Replaces:
- https://github.com/acmesh-official/acme.sh/pull/3207

**Pull request merged**
