### PR TITLE
Add wildcard certificate support for dns_constellix

### PR DESCRIPTION
**Pull request by woutd**
With these changes, the plugin will detect if the record already exists and update it instead of adding a new one (which fails). This adds support for certain wildcard certificates (#3143) where multiple TXT values should be added for the same `_sub_domain`.

I also decreased the TTL from 120 to 60 seconds and some minor cleanup.

I am using it in production already, but extra testing is always welcome.

### CODE REVIEW

**Comment by Neilpang** [comment]
can you please fix the CI checks first ?

https://github.com/woutd/acme.sh/actions/workflows/DNS.yml

**Comment by woutd** [comment]
I am following the instructions from https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Test

Repository Actions seemed to be enabled already on the fork, so I did not change anything there.

Next, in the "Secrets" menu I can choose "Environment" or "Action" secrets, the wiki does not specify this so I went with "Actions" as that seems to be the kind of default when clicking on the "New repository secret". So I created the following "Action secrets":

```
TokenName1 = CONSTELLIX_Key
TokenValue1 = XXX (hidden)
TokenName2 = CONSTELLIX_Secret
TokenValue2 = XXX (hidden)
TEST_DNS = dns_constellix
TestingDomain = foobar.rambla.eu
TEST_DNS_SLEEP = 120
```

Then I tried to retrigger the checks with an empty commit but it keeps failing with the same error.
Do I need to make them "Environments secrets" or do you know what I am doing wrong?

Screenshot_2021-03-14_16-23-13

**Comment by woutd** [comment]
I managed to add the required secrets to the forked repository, and re-run the workflow jobs. But it seems something goes wrong with the docker image:

`centos:latest [FAIL]`

Not sure how I can fix this.

**Comment by woutd** [comment]
I got it working, but it seems something goes wrong in the `_get_root` function on Solaris. Not sure what is the problem here.

**Comment by Neilpang** [comment]
you can use this project to debug on Solaris.

https://github.com/vmactions/shell-solaris

**Comment by woutd** [comment]
I managed to find the issue on Solaris. The problem is here:
`_domain_id=$(printf "%s\n" "$response" | _egrep_o "\"id\":[0-9]+" | cut -d ':' -f 2)`
While `[0-9]+` is a valid regex it does not seem to work on Solaris. I can replace it with `[0-9]*`.
(I could also use `[0-9]\{1,\}`, which is a bit more correct, but harder to read. Also, this one does not seem to work on the other operating systems.)

I suspect this to be an issue in a lot of other plugins as well:
`
grep "\[0-9\]+" dnsapi/* | wc -l
34
`

**Comment by woutd** [comment]
Needed some more changes... but finally got it fully working on Solaris.
Screenshot_2021-03-24_15-44-42

**Pull request merged**
