### PR TITLE
Add deploy hook for Lighttpd

### PR DESCRIPTION
**Pull request by DrDrrae**
#687 Support automatic issue hook for Lighttpd?

Created a deploy script for Lighttpd.  Currently the section to edit the conf file doesn't work and is commented out.

I'm certainly not a bash/sh scripting expert.  Any assistance would be greatly appreciated.

### CODE REVIEW

**Comment by Neilpang** [comment]
it seems like a  deploy hook,  not a issue hook, right ?

**Comment by DrDrrae** [comment]
That's correct.  It's a deploy hook, not an issue hook.

I understand it's not an exact answer for the issue.  I don't have the knowledge or experience with Shell to develop an issue hook.

**Comment by Neilpang** [comment]
please fix the format errors first.
https://travis-ci.org/Neilpang/acme.sh/jobs/261563167

**Comment by DrDrrae** [comment]
Removed the code which wasn't really being used for backing up and restoring the Lighttpd config file.  Also removed the commented out code for editing the config file as it didn't work anyway.

Changed the names of the files that it saved.  Let me know if this is okay or what it should be changed to.

**Comment by Tntdruid** [comment]
Does it works?

**Comment by gstrauss** [comment]
An different deploy/lighttpd.sh was committed Sep 2021.

Please review to see if this should be closed.

**Pull request closed without merging**
